-- CreateEnum
CREATE TYPE "CalendarSyncProvider" AS ENUM ('GOOGLE', 'APPLE');

-- CreateEnum
CREATE TYPE "CalendarSyncOperation" AS ENUM ('CREATE', 'UPDATE', 'DELETE');

-- CreateEnum
CREATE TYPE "CalendarSyncJobStatus" AS ENUM ('PENDING', 'PROCESSING', 'DONE', 'FAILED');

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "isBlocking" SET DEFAULT false,
ALTER COLUMN "autoGenerated" SET DEFAULT false;

-- CreateTable
CREATE TABLE "TaskCalendarSync" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "provider" "CalendarSyncProvider" NOT NULL,
    "externalEventId" TEXT NOT NULL,
    "lastSyncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TaskCalendarSync_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CalendarSyncJob" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "provider" "CalendarSyncProvider" NOT NULL,
    "operation" "CalendarSyncOperation" NOT NULL,
    "payload" JSONB,
    "status" "CalendarSyncJobStatus" NOT NULL DEFAULT 'PENDING',
    "errorMessage" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 5,
    "nextRetryAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMP(3),

    CONSTRAINT "CalendarSyncJob_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TaskCalendarSync_userId_idx" ON "TaskCalendarSync"("userId");

-- CreateIndex
CREATE INDEX "TaskCalendarSync_provider_idx" ON "TaskCalendarSync"("provider");

-- CreateIndex
CREATE UNIQUE INDEX "TaskCalendarSync_taskId_provider_key" ON "TaskCalendarSync"("taskId", "provider");

-- CreateIndex
CREATE INDEX "CalendarSyncJob_status_idx" ON "CalendarSyncJob"("status");

-- CreateIndex
CREATE INDEX "CalendarSyncJob_nextRetryAt_idx" ON "CalendarSyncJob"("nextRetryAt");

-- CreateIndex
CREATE INDEX "CalendarSyncJob_userId_idx" ON "CalendarSyncJob"("userId");

-- AddForeignKey
ALTER TABLE "TaskCalendarSync" ADD CONSTRAINT "TaskCalendarSync_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskCalendarSync" ADD CONSTRAINT "TaskCalendarSync_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
