import React from "react"
import Link from "next/link"

export const ARTICLES_1_5: Record<string, React.ReactNode> = {
  "verifactu-2026": (
    <div>
      <h2>Verifactu en 2026: por qué se aplazó a 2027 y qué te obliga ya</h2>
      <p>Verifactu es el sistema de facturación verificable que exige la normativa española para que cada factura emitida por software sea trazable e inalterable. La novedad de 2026 es el calendario: a finales de 2025 se aprobó un aplazamiento, así que la obligación entra <strong>el 1 de enero de 2027 para empresas y el 1 de julio de 2027 para autónomos</strong>. Los requisitos técnicos no han cambiado; solo las fechas. Aquí tienes qué te obliga, qué te exime y cuánto cuesta no adaptarse.</p>
      <h2>Qué es Verifactu (en una frase)</h2>
      <p>Es la parte del Reglamento que regula los Sistemas Informáticos de Facturación (RD 1007/2023 y Orden HAC/1177/2024). Obliga a que tu programa de facturación genere registros que <strong>no se puedan borrar ni manipular</strong> y, en modo Verifactu, los remita a la Agencia Tributaria. No es un impuesto nuevo ni un trámite que hagas tú a mano: es un requisito que debe cumplir el <strong>software</strong> que usas para facturar.</p>
      <blockquote><p><strong>Un matiz que conviene saber:</strong> la AEAT <strong>no emite un "certificado oficial" de Verifactu</strong>. El cumplimiento se acredita mediante una <strong>declaración responsable del fabricante</strong> del software (art. 29.2.j de la Ley General Tributaria). Por eso, cuando un programa dice "certificado por la AEAT", en rigor significa "el fabricante declara que cumple el RD 1007/2023". Pídele esa declaración responsable a tu proveedor y guárdala.</p></blockquote>
      <h2>Por qué se aplazó a 2027</h2>
      <p>El calendario original situaba la obligación en 2026. A finales de 2025 se aprobó un aplazamiento que mueve las fechas un año, dando más margen tanto a los obligados como a los fabricantes de software. Lo importante: <strong>solo cambió el calendario</strong>, no los requisitos técnicos del sistema.</p>
      <table><thead><tr><th>Obligado</th><th>Fecha desde la que es obligatorio</th></tr></thead><tbody><tr><td>Empresas (sujetas al Impuesto sobre Sociedades)</td><td>1 de enero de 2027</td></tr><tr><td>Autónomos y resto de obligados</td><td>1 de julio de 2027</td></tr></tbody></table>
      <h2>Qué te obliga ya (aunque la fecha sea 2027)</h2>
      <p>Que la obligación general llegue en 2027 no significa que puedas ignorarla:</p>
      <ul><li><strong>Si usas software de facturación, debe ir hacia un sistema conforme.</strong> Cuando llegue tu fecha, el programa tendrá que generar facturas con todos los elementos obligatorios. Elegir ahora una herramienta ya conforme te evita migrar con prisas.</li><li><strong>Cada factura emitida por software deberá llevar:</strong> huella o *hash*, encadenamiento con la factura anterior, código QR y, en modo Verifactu, la leyenda <strong>"VERI*FACTU"</strong> o "factura verificable".</li><li><strong>El encadenamiento importa.</strong> Cada registro se enlaza con el anterior, de forma que no se pueda colar ni eliminar una factura sin dejar rastro.</li><li><strong>La prohibición del "software de doble uso" ya está vigente.</strong> Si hoy usas un programa que permite borrar o alterar facturas sin dejar traza, ya eres sancionable bajo la Ley Antifraude, al margen de los plazos de Verifactu.</li></ul>
      <h2>Sanciones: las cifras reales</h2>
      <p>Aquí hay mucha confusión, así que vamos a las cantidades exactas que fija el artículo 201 bis de la Ley General Tributaria:</p>
      <ul><li><strong>50.000 € por ejercicio fiscal</strong> para el autónomo o empresa que <strong>use</strong> software no conforme o de doble uso. Es una multa <strong>fija y por año</strong>, no por factura: da igual que emitas mil facturas o una.</li><li><strong>150.000 € por ejercicio</strong> para el <strong>fabricante</strong> que produzca o comercialice software no conforme (o que lo publicite como compatible sin serlo).</li><li><strong>1.000 € por cada equipo o instalación</strong> en que se detecte un incumplimiento meramente formal del software.</li><li><strong>Falta del código QR</strong> o datos incorrectos en él: se enmarca en el incumplimiento de los deberes de facturación, con sanción del <strong>1 % del importe</strong> de las operaciones afectadas y un <strong>mínimo de 300 €</strong>.</li></ul>
      <p>No son multas simbólicas: el coste de no adaptarse supera con creces el de cambiar de programa a tiempo.</p>
      <h2>Quién está exento</h2>
      <ul><li><strong>País Vasco y Navarra:</strong> tienen régimen foral propio y su sistema es <strong>TicketBAI</strong>, no Verifactu.</li><li><strong>Quien factura 100 % a mano</strong>, sin ningún software. En la práctica, en cuanto usas un programa para facturar (incluido Word o Excel), entras en el ámbito de la norma.</li></ul>
      <h2>Verifactu no es lo mismo que la factura electrónica B2B</h2>
      <p>Es la confusión más habitual. Son <strong>dos obligaciones distintas</strong> que avanzan en paralelo:</p>
      <ul><li><strong>Verifactu</strong> (Ley Antifraude) regula *cómo* tu software registra y conserva cada factura: huella, QR, encadenamiento. Su uso es opcional en cuanto al envío automático, pero los requisitos técnicos son obligatorios.</li><li><strong>La factura electrónica B2B obligatoria</strong> (Ley Crea y Crece, desarrollada por el RD 238/2026) regula que las facturas entre empresas y autónomos sean electrónicas y estructuradas, con plazos que apuntan a octubre de 2027 y octubre de 2028.</li></ul>
      <p>Puedes estar sujeto a una, a la otra o a ambas. Lo desarrollamos en <Link href="/blog/factura-electronica-obligatoria">factura electrónica obligatoria</Link>.</p>
      <h2>Qué hacer ahora, sin agobios</h2>
      <ol><li>Comprueba si tu programa de facturación es (o será) conforme a Verifactu, y pídele al proveedor su <strong>declaración responsable</strong>.</li><li>Si facturas en Excel o en Word, ve pensando en dar el salto: esos métodos no generan huella ni QR.</li><li>No esperes a 2027 para decidir. Migrar con margen es barato; hacerlo a contrarreloj, junto a miles de autónomos a la vez, no.</li></ol>
      <h2>Preguntas frecuentes</h2>
      <p><strong>¿Verifactu es obligatorio en 2026?</strong> No. Tras el aplazamiento de finales de 2025, la obligación entra el 1 de enero de 2027 para empresas y el 1 de julio de 2027 para autónomos.</p>
      <p><strong>¿Tengo que enviar yo las facturas a Hacienda?</strong> No manualmente. Lo hace el software en modo Verifactu. Tu trabajo es usar un programa conforme.</p>
      <p><strong>Si facturo a mano en papel, ¿me afecta?</strong> No, mientras no uses ningún software para emitir facturas. En cuanto usas un programa, entras en el ámbito de la norma.</p>
      <p><strong>¿Cuánto es la multa por no cumplir Verifactu?</strong> 50.000 € por ejercicio para quien usa software no conforme; es fija, por año, no por factura. La falta de QR se sanciona aparte (1 % de las operaciones, mínimo 300 €).</p>
      <p><strong>¿Verifactu sustituye al modelo 303 o al 130?</strong> No. Verifactu regula la emisión de facturas; el <Link href="/blog/modelo-303">modelo 303</Link> y el <Link href="/blog/modelo-130">modelo 130</Link> siguen siendo tus declaraciones de IVA e IRPF.</p>
      <h2>En resumen</h2>
      <p>Verifactu llega en 2027, no en 2026, pero la decisión que sí puedes tomar ya es elegir un programa de facturación que cumpla de serie y que te entregue su declaración responsable. ClientLabs emite facturas conformes —con huella, QR y encadenamiento— sin que tengas que configurar nada técnico, para que llegues a tu fecha sin sustos.</p>
    </div>
  ),
  "factura-electronica-obligatoria": (
    <div>
      <h2>Factura electrónica obligatoria: a quién afecta y desde cuándo</h2>
      <p>La factura electrónica obligatoria entre empresas y autónomos (B2B) ya tiene reglamento: el <strong>Real Decreto 238/2026</strong>, publicado en el BOE el 31 de marzo de 2026, desarrolla por fin la Ley Crea y Crece. Falta el último paso —una orden ministerial que arranca el reloj—, pero el calendario ya apunta a <strong>octubre de 2027 para las grandes empresas y octubre de 2028 para pymes y autónomos</strong>. Y ojo: esto <strong>no es lo mismo que Verifactu</strong>. Aquí tienes qué cambia y cómo prepararte sin agobios.</p>
      <h2>Qué es (y qué no)</h2>
      <p>La Ley Crea y Crece obliga a que las facturas <strong>entre empresas y autónomos (B2B)</strong> sean electrónicas y <strong>estructuradas</strong>: un fichero que las máquinas puedan leer y procesar de forma automática, no un PDF ni un papel. El objetivo declarado es reducir la morosidad, porque el sistema obliga además a <strong>comunicar el estado de cada factura</strong> (aceptada, rechazada, pagada). No afecta a las facturas a particulares (B2C).</p>
      <p>Un punto clave: <strong>una factura en PDF, aunque la envíes por email, no es una factura electrónica estructurada</strong> a estos efectos. El reglamento exige formatos como Facturae, UBL, CII o EDIFACT, conforme a la norma europea EN16931.</p>
      <h2>A quién afecta y desde cuándo</h2>
      <p>El despliegue es <strong>escalonado por volumen de facturación</strong>, y los plazos se cuentan desde la entrada en vigor de la orden ministerial de desarrollo (prevista para el 1 de octubre de 2026):</p>
      <table><thead><tr><th>Obligado</th><th>Plazo (según el calendario previsto)</th></tr></thead><tbody><tr><td>Empresas con facturación &gt; 8 millones €/año</td><td>~12 meses → <strong>octubre de 2027</strong></td></tr><tr><td>Resto de empresas, pymes y autónomos</td><td>~24 meses → <strong>octubre de 2028</strong></td></tr></tbody></table>
      <p>Como autónomo, tu fecha de referencia es <strong>octubre de 2028</strong>, salvo que tu facturación supere los 8 millones de euros. Las fechas definitivas dependen de la publicación final de la orden en el BOE, pero el reglamento (RD 238/2026) ya está aprobado y en vigor desde abril de 2026.</p>
      <h2>Cómo funcionará en la práctica</h2>
      <ul><li><strong>Formato estructurado obligatorio:</strong> Facturae, UBL, CII o EDIFACT. Durante los primeros 12 meses se podrá acompañar la factura de una copia en PDF legible, pero el PDF no sustituye al fichero estructurado.</li><li><strong>Dos vías de intercambio:</strong> plataformas privadas (que deberán estar interconectadas gratuitamente entre sí) o la <strong>solución pública gratuita de la AEAT</strong>, pensada para quien factura poco volumen.</li><li><strong>Comunicación de estados:</strong> el destinatario deberá comunicar la aceptación o el rechazo de la factura y la fecha de pago, en un plazo de <strong>4 días naturales</strong> (excluyendo fines de semana y festivos). En ausencia de rechazo, se presume aceptada.</li></ul>
      <h2>La confusión clave: Crea y Crece ≠ Verifactu</h2>
      <p>Son <strong>dos obligaciones distintas</strong> que avanzan en paralelo y que mucha gente mezcla:</p>
      <table><thead><tr><th></th><th>Factura electrónica B2B (Crea y Crece)</th><th>Verifactu (RD 1007/2023)</th></tr></thead><tbody><tr><td>Qué regula</td><td>Que la factura entre empresas sea <strong>electrónica y estructurada</strong>, y el seguimiento de su estado</td><td>Cómo el <strong>software</strong> registra y conserva cada factura (huella, QR, encadenamiento)</td></tr><tr><td>A quién</td><td>Operaciones B2B</td><td>Quien factura con software</td></tr><tr><td>Norma</td><td>Ley 18/2022 + RD 238/2026</td><td>Ley 11/2021 + RD 1007/2023</td></tr><tr><td>Fechas</td><td>Oct 2027 (&gt;8M€) / Oct 2028 (resto)</td><td>Empresas 1/1/2027, autónomos 1/7/2027</td></tr></tbody></table>
      <p>Puedes estar sujeto a una, a la otra o a ambas. Tienes el detalle de Verifactu en <Link href="/blog/verifactu-2026">Verifactu en 2026</Link>.</p>
      <h2>Qué hacer ahora</h2>
      <ol><li><strong>No confundas plazos:</strong> Verifactu llega en 2027; la factura electrónica B2B, hacia 2028 para autónomos. Son fechas y obligaciones distintas.</li><li><strong>Usa software que emita en formato electrónico estructurado</strong> y conforme a Verifactu, para no tener que migrar dos veces.</li><li><strong>Revisa tus datos de clientes y proveedores:</strong> el sistema necesita NIF, direcciones y datos completos para funcionar. Tenerlos sucios ahora será un problema cuando llegue la obligación.</li></ol>
      <h2>Preguntas frecuentes</h2>
      <p><strong>¿La factura electrónica B2B ya es obligatoria?</strong> Todavía no para emitir, pero el reglamento (RD 238/2026) ya está publicado. La obligación efectiva llegará hacia octubre de 2027 (grandes empresas) y octubre de 2028 (pymes y autónomos), una vez se publique la orden ministerial de desarrollo.</p>
      <p><strong>¿Tengo que hacer factura electrónica a mis clientes particulares?</strong> No. La obligación de Crea y Crece es solo para operaciones entre empresas y autónomos (B2B).</p>
      <p><strong>¿Un PDF cuenta como factura electrónica?</strong> No. Tiene que ser un fichero estructurado (Facturae, UBL, CII o EDIFACT). El PDF solo vale como copia legible durante un periodo transitorio.</p>
      <p><strong>¿Es lo mismo que Verifactu?</strong> No. Verifactu regula cómo tu software registra las facturas; Crea y Crece, que las facturas B2B sean electrónicas y estructuradas, con seguimiento de su estado de pago.</p>
      <p><strong>¿Cuánto cuesta incumplir?</strong> La Ley Crea y Crece prevé sanciones de hasta 10.000 € por no emitir, recibir o comunicar el estado de las facturas electrónicas cuando sea obligatorio.</p>
      <h2>En resumen</h2>
      <p>La factura electrónica B2B ya no es un "algún día": tiene reglamento publicado y un calendario que apunta a 2027-2028. Tener un software preparado para emitir en formato estructurado y conforme a Verifactu te evita migrar dos veces y llegar con prisas. ClientLabs emite facturas conformes con Verifactu y está preparado para el formato electrónico estructurado, listo para lo que venga.</p>
    </div>
  ),
  "errores-factura-autonomo": (
    <div>
      <h2>7 errores de factura que más multas generan al autónomo</h2>
      <p>La mayoría de las sanciones por facturación no vienen de fraudes, sino de descuidos: numeración con saltos, datos incompletos o un IVA mal calculado. Estos son los siete errores que más caro salen a un autónomo y cómo evitarlos antes de que lleguen al trimestre o a una inspección.</p>
      <h2>1. Numeración con saltos o repetida</h2>
      <p>La factura debe ir con <strong>número correlativo y sin huecos</strong>. Saltarte un número o repetirlo es una señal de alarma para Hacienda, porque sugiere que falta facturación. Solución: numeración automática y series claras (<code>2026-001</code>, <code>2026-002</code>). Si usas series distintas (una para facturas y otra para rectificativas), cada una debe ir seguida.</p>
      <h2>2. Datos obligatorios incompletos</h2>
      <p>Falta el NIF del cliente, la dirección o el desglose del IVA. Una factura incompleta <strong>no es deducible</strong> para tu cliente y solo es subsanable hasta cierto punto. Revisa la lista completa en <Link href="/blog/como-hacer-una-factura">cómo hacer una factura</Link>.</p>
      <h2>3. Tipo de IVA equivocado</h2>
      <p>Aplicar el 21 % donde correspondía el 10 % (o al revés). El error se arrastra al <Link href="/blog/modelo-303">modelo 303</Link> y puede acabar en una regularización con recargo. Ten claros los tres tipos: 21 % general, 10 % reducido y 4 % superreducido.</p>
      <h2>4. Olvidar la retención de IRPF</h2>
      <p>Si eres profesional y facturas a empresas o a otros autónomos, debes aplicar retención (15 %, o 7 % si eres nuevo). Olvidarla descuadra tu IRPF y el del cliente. Lo aclaramos en <Link href="/blog/retencion-irpf-factura">qué retención poner</Link>.</p>
      <h2>5. Borrar una factura ya emitida</h2>
      <p>Si te equivocas, <strong>no la elimines</strong>: emite una <strong>factura rectificativa</strong>. Borrar rompe la numeración y, con Verifactu, el encadenamiento. Con software conforme, además, cada modificación queda registrada: borrar sin más será directamente imposible.</p>
      <h2>6. Facturar sin software conforme (de cara a 2027)</h2>
      <p>A partir del 1 de julio de 2027, las facturas emitidas por software deberán llevar huella, QR y encadenamiento (Verifactu). Usar un programa no conforme expone a una multa <strong>fija de 50.000 € por ejercicio</strong> (no por factura), y la falta del código QR se sanciona aparte con el <strong>1 % de las operaciones afectadas, mínimo 300 €</strong>. Contexto completo en <Link href="/blog/verifactu-2026">Verifactu en 2026</Link>.</p>
      <h2>7. No guardar las facturas</h2>
      <p>Sin el justificante, no puedes deducir un gasto ni defender un ingreso. Hacienda puede revisar hasta 4 años (art. 66 LGT), pero el Código de Comercio obliga a conservar la documentación 6 años (art. 30): guarda todo <strong>un mínimo de 6 años</strong>.</p>
      <h2>Tabla resumen</h2>
      <table><thead><tr><th>Error</th><th>Riesgo</th><th>Cómo evitarlo</th></tr></thead><tbody><tr><td>Numeración con saltos</td><td>Factura inválida</td><td>Numeración automática</td></tr><tr><td>Datos incompletos</td><td>No deducible para el cliente</td><td>Plantilla con todos los campos</td></tr><tr><td>IVA mal aplicado</td><td>Regularización + recargo</td><td>Tipos predefinidos (21/10/4 %)</td></tr><tr><td>Sin retención IRPF</td><td>IRPF descuadrado</td><td>Reglas por tipo de cliente</td></tr><tr><td>Borrar facturas</td><td>Rompe numeración/encadenamiento</td><td>Factura rectificativa</td></tr><tr><td>Software no conforme</td><td>50.000 €/ejercicio</td><td>Programa con Verifactu</td></tr><tr><td>No archivar</td><td>Pierdes la deducción</td><td>Guardar mínimo 6 años</td></tr></tbody></table>
      <h2>Preguntas frecuentes</h2>
      <p><strong>¿Qué pasa si me salto un número de factura?</strong> La numeración debe ser correlativa; un salto puede invalidar la factura y llamar la atención de Hacienda. Si anulas una factura, usa una rectificativa, no la borres.</p>
      <p><strong>¿Puedo corregir una factura ya enviada?</strong> Sí, con una factura rectificativa. Nunca borrándola.</p>
      <p><strong>¿Cuánto puede costarme facturar mal?</strong> Con Verifactu, hasta 50.000 € por ejercicio si usas software no conforme, más la sanción por falta de QR (1 % de las operaciones, mínimo 300 €). Antes de eso, recargos por errores de IVA o IRPF.</p>
      <p><strong>¿Cuánto tiempo guardo las facturas?</strong> Hacienda revisa hasta 4 años (art. 66 LGT); por el Código de Comercio (art. 30), conserva la documentación un mínimo de 6 años.</p>
      <h2>En resumen</h2>
      <p>Casi todos estos errores desaparecen con un programa que numere solo, calcule los impuestos y conserve cada factura sin que puedas alterarla. ClientLabs hace ese trabajo por ti y emite conforme a Verifactu, para que el trimestre no traiga sorpresas ni la inspección, sustos.</p>
    </div>
  ),
  "modelo-303": (
    <div>
      <h2>Modelo 303: cómo calcular tu IVA sin equivocarte de casilla</h2>
      <p>El modelo 303 es la declaración trimestral del IVA: ingresas a Hacienda el <strong>IVA que has cobrado</strong> a tus clientes menos el <strong>IVA que has pagado</strong> en tus gastos. Si cobraste más del que pagaste, ingresas la diferencia; si pagaste más, queda a compensar o a devolver. Suena simple, y lo es, pero hay un par de casillas donde la gente se equivoca y acaba pagando de más o ganándose una regularización. Aquí está el cálculo y cómo evitar esos errores.</p>
      <h2>La fórmula del 303</h2>
      <p><strong>IVA repercutido (el que cobras) − IVA soportado deducible (el que pagas) = resultado</strong></p>
      <ul><li>Resultado <strong>positivo</strong> → ingresas esa cantidad a Hacienda.</li><li>Resultado <strong>negativo</strong> → queda a compensar en los siguientes trimestres (o a devolver en el último del año).</li></ul>
      <h2>Un ejemplo completo</h2>
      <p>Imagina un trimestre normal:</p>
      <ul><li>Facturas emitidas: 10.000 € de base imponible → <strong>IVA repercutido (21 %): 2.100 €</strong></li><li>Gastos con factura: 3.000 € de base → <strong>IVA soportado (21 %): 630 €</strong></li><li><strong>Resultado: 2.100 − 630 = 1.470 € a ingresar</strong></li></ul>
      <p>Si ese mismo trimestre hubieras tenido pocos ingresos y una compra grande (por ejemplo, un equipo de 5.000 € + IVA), el IVA soportado podría superar al repercutido y el resultado saldría negativo: en ese caso, lo arrastras "a compensar".</p>
      <h2>Las casillas que más se confunden</h2>
      <ul><li><strong>IVA repercutido:</strong> el de tus facturas emitidas, separado por tipo. En España hay tres: <strong>21 %</strong> (general), <strong>10 %</strong> (reducido: hostelería, transporte de viajeros, ciertas reformas…) y <strong>4 %</strong> (superreducido: pan, leche, libros, medicamentos…). Mézclalos mal y el resultado se descuadra.</li><li><strong>IVA soportado deducible:</strong> aquí está el error más caro. Solo puedes deducir el IVA de gastos <strong>vinculados a tu actividad y con factura completa</strong> a tu nombre. Un ticket simple no basta, y un gasto personal colado tampoco. Revisa <Link href="/blog/gastos-deducibles-autonomo-2026">qué puedes deducir</Link>.</li><li><strong>Resultado:</strong> la diferencia. Si sale negativo, marca la casilla "a compensar" (no pierdes ese IVA: lo descuentas en trimestres futuros).</li></ul>
      <h2>Plazos trimestrales en 2026</h2>
      <table><thead><tr><th>Trimestre</th><th>Periodo</th><th>Plazo de presentación</th></tr></thead><tbody><tr><td>1T</td><td>enero – marzo</td><td>1 – 20 de abril</td></tr><tr><td>2T</td><td>abril – junio</td><td>1 – 20 de julio</td></tr><tr><td>3T</td><td>julio – septiembre</td><td>1 – 20 de octubre</td></tr><tr><td>4T</td><td>octubre – diciembre</td><td>1 – 30 de enero de 2027</td></tr></tbody></table>
      <p>Si el plazo termina en festivo o fin de semana, pasa al siguiente día hábil. Si <strong>domicilias</strong> el pago, resta unos 5 días al plazo. Y recuerda: en enero, además del 4T, se presenta el <strong>modelo 390</strong> (resumen anual del IVA), hasta el 30 de enero.</p>
      <h2>Los 4 errores que cuestan dinero</h2>
      <ol><li><strong>Deducir IVA de gastos no afectos a la actividad.</strong> Es la casilla que más revisa Hacienda. Si el gasto no está claramente vinculado a tu trabajo, no lo metas.</li><li><strong>No separar el IVA por tipos.</strong> Si facturas al 21 % y al 10 %, cada tipo va en su casilla. Sumarlo todo al 21 % falsea el resultado.</li><li><strong>Olvidar facturas del trimestre.</strong> Cualquier factura emitida o recibida que no registres descuadra el 303 frente a tus libros.</li><li><strong>Presentar tarde.</strong> Genera un recargo automático que crece con el retraso. Es el error más fácil de evitar y el más absurdo de cometer.</li></ol>
      <h2>Preguntas frecuentes</h2>
      <p><strong>¿Qué es el modelo 303?</strong> La autoliquidación trimestral del IVA: el IVA que has cobrado en tus facturas menos el IVA deducible que has pagado en tus gastos.</p>
      <p><strong>¿Cuándo se presenta el 303?</strong> En abril, julio, octubre y enero, dentro de los 20 primeros días (hasta el 30 en el cuarto trimestre). Si domicilias, unos 5 días antes.</p>
      <p><strong>¿Qué pasa si el resultado sale negativo?</strong> Lo compensas en los siguientes trimestres del año. En el cuarto trimestre, si sigue saliendo a tu favor, puedes solicitar la devolución.</p>
      <p><strong>¿El 303 es lo mismo que el 130?</strong> No. El 303 es el IVA; el <Link href="/blog/modelo-130">modelo 130</Link> es el adelanto del IRPF. Son dos impuestos distintos que se presentan en los mismos plazos.</p>
      <p><strong>¿Qué IVA de mis gastos puedo deducir?</strong> El de gastos vinculados a tu actividad y respaldados con factura completa a tu nombre. El IVA de gastos mixtos (como el coche) tiene reglas especiales: lo vemos en <Link href="/blog/gastos-deducibles-autonomo-2026">gastos deducibles</Link>.</p>
      <p><strong>¿Tengo que presentar el 303 aunque no haya tenido actividad?</strong> Sí. Si estás de alta, presentas el 303 cada trimestre aunque sea "sin actividad" (a cero). No presentarlo se considera incumplimiento.</p>
      <h2>En resumen</h2>
      <p>El 303 es restar dos cifras bien llevadas. El truco no está en la fórmula, sino en tener cada factura emitida y cada gasto registrado con su IVA correcto. ClientLabs te muestra el IVA repercutido y el soportado del trimestre ya separados por tipo y listos para el 303, de modo que solo tengas que revisar y presentar, sin cuadrar nada a mano.</p>
    </div>
  ),
  "cuota-autonomos-2026": (
    <div>
      <h2>Cuota de autónomos 2026: cuánto pagas según tus ingresos (tramos)</h2>
      <p>Desde 2023, los autónomos cotizan por <strong>ingresos reales</strong>: cuanto mayor es tu rendimiento neto, más alta es tu base mínima y, por tanto, tu cuota mensual a la Seguridad Social. En 2026 sigue ese sistema de <strong>15 tramos</strong>, con las cuotas congeladas respecto a 2025 y una única novedad relevante (el MEI sube al 0,9 %). Aquí tienes cuánto se paga en cada tramo, la tarifa plana para quien empieza y cómo estimar tu cuota sin sorpresas.</p>
      <h2>Cómo funciona la cotización por ingresos reales</h2>
      <p>El sistema es más sencillo de lo que parece si lo ves en cuatro pasos:</p>
      <ol><li><strong>Estimas tu rendimiento neto</strong> (ingresos − gastos deducibles − cuotas RETA − deducción genérica del 7 %, o del 3 % si eres societario) y lo divides entre 12 para tener tu rendimiento mensual.</li><li>Ese rendimiento te sitúa en un <strong>tramo</strong>, que tiene una base mínima y una máxima.</li><li><strong>Eliges una base</strong> dentro de tu tramo (si quieres mejores prestaciones futuras, puedes elegir una superior) y sobre ella se calcula la cuota.</li><li>Al año siguiente, la Seguridad Social <strong>regulariza</strong>: cruza tus rendimientos reales con Hacienda y te devuelve o te reclama la diferencia.</li></ol>
      <p>El error más común es confundir <strong>facturación con rendimiento neto</strong>. El tramo se calcula sobre lo que ganas *después* de gastos, no sobre lo que ingresas.</p>
      <h2>La tabla de tramos 2026</h2>
      <p>Las cuotas de 2026 las fija la <strong>Orden PJC/297/2026</strong> (BOE de 31 de marzo de 2026) y están <strong>congeladas</strong> respecto a 2025: la propuesta de subirlas se rechazó en el Congreso. Hay 15 tramos, repartidos entre una tabla reducida (rendimientos por debajo de 1.166,70 €/mes) y una tabla general. El tipo de cotización total ronda el 31,5 %, e incluye contingencias comunes (28,30 %), profesionales (1,30 %), cese de actividad, formación y el MEI (0,90 %).</p>
      <table><thead><tr><th>Rendimiento neto mensual</th><th>Cuota base 2026/mes</th><th>Cuota real con MEI</th></tr></thead><tbody><tr><td>≤ 670 € (tramo más bajo)</td><td>~200 €</td><td>~206 €</td></tr><tr><td>Tramos intermedios</td><td>entre 200 € y 590 €</td><td>+ MEI según base</td></tr><tr><td>&gt; 6.000 € (tramo más alto, base mínima)</td><td>~590 €</td><td>~607 €</td></tr></tbody></table>
      <p>Las cifras de la columna central son las cuotas "base" que comunica el Gobierno (cotizando por la base mínima de cada tramo). La columna de la derecha incluye el <strong>MEI del 0,9 %</strong>, que es lo que de verdad sale de tu cuenta: por eso la cuota mínima real de 2026 ronda los <strong>206 €/mes</strong>, no los 200 € redondos.</p>
      <p>Dos apuntes:</p>
      <ul><li>Si eliges una <strong>base superior</strong> a la mínima de tu tramo (para mejorar tu pensión futura), la cuota sube. La base máxima absoluta de 2026 es de <strong>5.101,20 €/mes</strong>, lo que llevaría la cuota hasta unos 1.607 €/mes.</li><li>El <strong>MEI</strong> seguirá subiendo 0,1 puntos cada año hasta el <strong>1,2 % en 2029</strong>. Lo asume íntegro el autónomo.</li></ul>
      <h2>La tarifa plana para nuevos autónomos</h2>
      <p>Si te das de alta por primera vez (o llevas 2 años o más sin estar en el RETA), puedes acogerte a la <strong>tarifa plana de 80 €/mes</strong> durante los <strong>12 primeros meses</strong>, sea cual sea el tramo que te correspondería por tus ingresos. Tres detalles que conviene saber:</p>
      <ul><li>Esos <strong>80 € son planos y no incluyen el MEI</strong>: es la cuota completa que pagas el primer año.</li><li>Es <strong>prorrogable otros 12 meses</strong> si tus rendimientos netos del primer año quedan por debajo del Salario Mínimo Interprofesional (SMI).</li><li>Para acogerte no puedes haber estado de alta en el RETA en los <strong>2 años anteriores</strong> (3 años si ya disfrutaste antes de esta bonificación).</li></ul>
      <p>Además, varias comunidades autónomas (Andalucía, Madrid, Galicia, Murcia, La Rioja…) tienen una <strong>"cuota cero"</strong> que cubre esos 80 € y deja tu pago en 0 € durante el periodo bonificado. El detalle del alta lo tienes en <Link href="/blog/darse-de-alta-como-autonomo-2026">cómo darte de alta como autónomo</Link>.</p>
      <h2>Cómo estimar tu cuota en 3 pasos</h2>
      <ol><li><strong>Calcula tu rendimiento neto medio:</strong> ingresos anuales − gastos deducibles − cuotas RETA pagadas, y aplica la deducción genérica del 7 %. Divide entre 12.</li><li><strong>Busca ese rendimiento en la tabla de tramos</strong> de 2026 para ver tu cuota.</li><li><strong>Ajusta si tus ingresos varían:</strong> puedes <strong>cambiar de base hasta 6 veces al año</strong> desde el portal Import@ss, con efecto el día 1 del mes siguiente. Es la mejor forma de no llevarte un susto en la regularización.</li></ol>
      <p>Llevar bien tus ingresos y <Link href="/blog/gastos-deducibles-autonomo-2026">gastos deducibles</Link> es lo que te da el rendimiento neto real, que es la base de todo este cálculo.</p>
      <h2>Preguntas frecuentes</h2>
      <p><strong>¿Cuánto paga un autónomo en 2026?</strong> Cotizando por la base mínima de cada tramo, entre unos 206 €/mes (rendimientos ≤ 670 €/mes, con el MEI incluido) y unos 590-607 €/mes (más de 6.000 €/mes). Lo fija la Orden PJC/297/2026 y las cuotas están congeladas respecto a 2025.</p>
      <p><strong>¿Cuál es la cuota mínima de autónomo en 2026?</strong> Unos 206 €/mes en el tramo más bajo, con el MEI del 0,9 % ya incluido. Sin contar el MEI, la cifra "base" que se comunica es de 200 €.</p>
      <p><strong>¿Qué es la tarifa plana y cuánto es en 2026?</strong> 80 €/mes durante los 12 primeros meses para nuevos autónomos, sin MEI, prorrogable otros 12 meses si tus rendimientos no superan el SMI. En varias comunidades, la "cuota cero" la deja en 0 €.</p>
      <p><strong>¿Puedo cambiar mi cuota si gano menos de lo previsto?</strong> Sí. Puedes cambiar la base de cotización hasta 6 veces al año. Si aun así pagaste de más, la Seguridad Social te devuelve la diferencia en la regularización anual.</p>
      <p><strong>¿Qué pasa si me equivoco al estimar mis ingresos?</strong> No pasa nada grave: la Seguridad Social regulariza a año vencido cruzando tus rendimientos reales con Hacienda. Si pagaste de menos, te reclama la diferencia; si pagaste de más, te la devuelve automáticamente.</p>
      <h2>En resumen</h2>
      <p>Tu cuota depende de lo que ganas de verdad, así que conocer tu rendimiento neto real es lo único que necesitas para anticiparla. En 2026 las cuotas siguen congeladas, el MEI sube ligeramente y la tarifa plana de 80 € sigue siendo el mejor aliado de quien empieza. ClientLabs te mantiene ingresos y gastos al día para que estimes tu tramo en cualquier momento y ajustes tu base antes de que llegue la regularización.</p>
    </div>
  ),
}
