export type ArticleMeta = {
  slug: string
  title: string
  category: string
  categoryKey: "normativa" | "guia" | "comparativa" | "tutorial" | "negocio"
  categoryColor: string
  readTime: string
  publishedAt: string
  description: string
  tags: string[]
  relatedSlugs: string[]
  /** Ruta de la miniatura, p.ej. "/blog/verifactu-2026.png" (ponla en public/blog/). Si se omite, se muestra el placeholder. */
  coverImage?: string
}

export const ARTICLES: ArticleMeta[] = [
  {
    slug: "verifactu-2026",
    title: "Verifactu en 2026: por qué se aplazó a 2027 y qué te obliga ya",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "4 min",
    publishedAt: "2026-05-01",
    description: "Verifactu se aplazó: empresas el 1 de enero de 2027 y autónomos el 1 de julio de 2027. Qué cambia, qué requisitos siguen vigentes y las sanciones.",
    tags: ["verifactu 2026", "autónomos", "2026"],
    relatedSlugs: ["factura-electronica-obligatoria", "errores-factura-autonomo", "como-hacer-una-factura", "mejores-programas-facturacion-autonomos-2026", "verifactu-en-clientlabs"],
  },
  {
    slug: "factura-electronica-obligatoria",
    title: "Factura electrónica obligatoria: a quién afecta y desde cuándo",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "4 min",
    publishedAt: "2026-05-02",
    description: "Factura electrónica obligatoria entre empresas (Ley Crea y Crece): a quién afecta, plazos de 1 y 2 años y en qué se diferencia de Verifactu.",
    tags: ["factura electrónica obligatoria", "autónomos"],
    relatedSlugs: ["verifactu-2026", "como-hacer-una-factura", "errores-factura-autonomo", "mejores-programas-facturacion-autonomos-2026", "calendario-fiscal-autonomo-2026"],
  },
  {
    slug: "errores-factura-autonomo",
    title: "7 errores de factura que más multas generan al autónomo",
    category: "Guía",
    categoryKey: "guia",
    categoryColor: "bg-emerald-50 text-emerald-700",
    readTime: "4 min",
    publishedAt: "2026-04-28",
    description: "Los 7 errores de facturación que más sanciones y problemas causan a los autónomos en España, con cómo detectarlos y evitarlos antes del trimestre.",
    tags: ["errores facturación autónomo", "autónomos"],
    relatedSlugs: ["como-hacer-una-factura", "retencion-irpf-factura", "modelo-303", "verifactu-2026", "facturar-en-excel-2026"],
  },
  {
    slug: "modelo-303",
    title: "Modelo 303: cómo calcular tu IVA sin equivocarte de casilla",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "4 min",
    publishedAt: "2026-04-25",
    description: "Modelo 303 de IVA: qué es, cómo se calcula (IVA repercutido menos soportado), las casillas clave y los plazos trimestrales de 2026. Con ejemplo.",
    tags: ["modelo 303", "autónomos"],
    relatedSlugs: ["modelo-130", "gastos-deducibles-autonomo-2026", "calendario-fiscal-autonomo-2026", "retencion-irpf-factura", "como-hacer-una-factura"],
  },
  {
    slug: "cuota-autonomos-2026",
    title: "Cuota de autónomos 2026: cuánto pagas según tus ingresos (tramos)",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "4 min",
    publishedAt: "2026-04-20",
    description: "Cuota de autónomos 2026 por ingresos reales: cómo funcionan los tramos, la tarifa plana para nuevos y cómo estimar lo que pagarás cada mes.",
    tags: ["cuota autónomos 2026", "autónomos", "2026"],
    relatedSlugs: ["darse-de-alta-como-autonomo-2026", "gastos-deducibles-autonomo-2026", "calendario-fiscal-autonomo-2026", "modelo-130", "modelo-303"],
  },
  {
    slug: "sistema-de-leads-simple",
    title: "Cómo dejar de perder clientes potenciales: un sistema de leads simple",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "4 min",
    publishedAt: "2026-04-18",
    description: "Un sistema de leads simple para autónomos: captar, clasificar y hacer seguimiento sin que se enfríe ningún cliente potencial. En 4 pasos.",
    tags: ["sistema de leads autónomos", "autónomos"],
    relatedSlugs: ["que-es-un-crm", "pipeline-de-clientlabs", "conseguir-clientes-por-internet", "clientes-y-proveedores-centralizados", "mejores-crm-gratis-autonomos"],
  },
  {
    slug: "clientes-y-proveedores-centralizados",
    title: "Clientes y proveedores sin caos: todo centralizado en un sitio",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "4 min",
    publishedAt: "2026-04-15",
    description: "Cómo centralizar clientes y proveedores en un solo lugar para no perder datos ni tiempo: ficha única, historial y documentos enlazados.",
    tags: ["centralizar clientes y proveedores", "autónomos"],
    relatedSlugs: ["que-es-un-crm", "sistema-de-leads-simple", "migrar-de-excel-a-clientlabs", "gastos-deducibles-autonomo-2026", "pipeline-de-clientlabs"],
  },
  {
    slug: "que-es-un-crm",
    title: "Qué es un CRM (y por qué tu Excel y tu agenda se quedan cortos)",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "4 min",
    publishedAt: "2026-04-10",
    description: "Qué es un CRM explicado para autónomos: para qué sirve, qué problemas resuelve frente a Excel y la agenda, y cuándo te empieza a hacer falta.",
    tags: ["qué es un CRM", "autónomos"],
    relatedSlugs: ["sistema-de-leads-simple", "clientes-y-proveedores-centralizados", "mejores-crm-gratis-autonomos", "pipeline-de-clientlabs", "conseguir-clientes-por-internet"],
  },
  {
    slug: "conseguir-clientes-por-internet",
    title: "Cómo conseguir clientes por internet sin gastar en anuncios",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "4 min",
    publishedAt: "2026-04-05",
    description: "Cómo conseguir clientes por internet sin pagar publicidad: canales orgánicos que funcionan para autónomos y cómo no perder los leads que llegan.",
    tags: ["conseguir clientes por internet", "autónomos"],
    relatedSlugs: ["sistema-de-leads-simple", "que-es-un-crm", "pipeline-de-clientlabs", "kit-digital-2026", "clientes-y-proveedores-centralizados"],
  },
  {
    slug: "calendario-fiscal-autonomo-2026",
    title: "Calendario fiscal del autónomo 2026: todas las fechas clave",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "4 min",
    publishedAt: "2026-04-01",
    description: "Calendario fiscal del autónomo 2026: fechas de IVA (303), IRPF (130), resúmenes anuales y renta, para presentar a tiempo y evitar recargos.",
    tags: ["calendario fiscal autónomo 2026", "autónomos", "2026"],
    relatedSlugs: ["modelo-303", "modelo-130", "cuota-autonomos-2026", "gastos-deducibles-autonomo-2026", "darse-de-alta-como-autonomo-2026"],
  },
  {
    slug: "mejores-programas-facturacion-autonomos-2026",
    title: "Los 8 mejores programas de facturación para autónomos en 2026 (con Verifactu)",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "4 min",
    publishedAt: "2026-03-28",
    description: "Comparamos 8 programas de facturación para autónomos en 2026: cuáles son conformes con Verifactu, para qué perfil sirve cada uno y qué evitar.",
    tags: ["mejores programas de facturación autónomos", "autónomos", "2026"],
    relatedSlugs: ["verifactu-2026", "clientlabs-vs-holded", "alternativas-facturaplus", "facturar-en-excel-2026", "como-hacer-una-factura"],
  },
  {
    slug: "clientlabs-vs-holded",
    title: "ClientLabs vs Holded: cuál te conviene según tu tipo de negocio",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "4 min",
    publishedAt: "2026-03-25",
    description: "ClientLabs vs Holded en 2026: diferencias reales en facturación, CRM, contabilidad y curva de aprendizaje. Cuál encaja según tu tipo de negocio.",
    tags: ["ClientLabs vs Holded", "autónomos"],
    relatedSlugs: ["mejores-programas-facturacion-autonomos-2026", "verifactu-2026", "que-es-un-crm", "migrar-de-excel-a-clientlabs", "alternativas-facturaplus"],
  },
  {
    slug: "alternativas-facturaplus",
    title: "FacturaPlus está obsoleto: 6 alternativas modernas con Verifactu",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "4 min",
    publishedAt: "2026-03-15",
    description: "FacturaPlus se quedó atrás y no encaja con Verifactu. Aquí tienes 6 alternativas modernas para autónomos y pymes, con sus puntos fuertes y para quién.",
    tags: ["alternativas a FacturaPlus", "autónomos"],
    relatedSlugs: ["mejores-programas-facturacion-autonomos-2026", "verifactu-2026", "facturar-en-excel-2026", "migrar-de-excel-a-clientlabs", "clientlabs-vs-holded"],
  },
  {
    slug: "mejores-crm-gratis-autonomos",
    title: "Los mejores CRM gratis para autónomos (y cuándo se quedan cortos)",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "4 min",
    publishedAt: "2026-03-10",
    description: "Los mejores CRM gratis para autónomos en 2026, qué incluyen de verdad y en qué momento un plan gratuito se te queda corto y conviene dar el salto.",
    tags: ["mejor CRM gratis autónomos", "autónomos"],
    relatedSlugs: ["que-es-un-crm", "sistema-de-leads-simple", "clientes-y-proveedores-centralizados", "pipeline-de-clientlabs", "mejores-programas-facturacion-autonomos-2026"],
  },
  {
    slug: "facturar-en-excel-2026",
    title: "Facturar en Excel en 2026: por qué te acaba saliendo caro",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "4 min",
    publishedAt: "2026-03-05",
    description: "Facturar en Excel sigue siendo legal en 2026, pero no cumplirá Verifactu y te expone a errores y multas. Qué riesgos asumes y cuándo dar el salto.",
    tags: ["facturar en Excel", "autónomos", "2026"],
    relatedSlugs: ["verifactu-2026", "migrar-de-excel-a-clientlabs", "mejores-programas-facturacion-autonomos-2026", "como-hacer-una-factura", "errores-factura-autonomo"],
  },
  {
    slug: "primera-factura-clientlabs",
    title: "Tu primera factura legal en ClientLabs en menos de 10 minutos",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "4 min",
    publishedAt: "2026-03-01",
    description: "Cómo emitir tu primera factura legal en ClientLabs en menos de 10 minutos: alta de cliente, conceptos, IVA, retención y factura conforme a Verifactu.",
    tags: ["primera factura ClientLabs", "autónomos"],
    relatedSlugs: ["como-hacer-una-factura", "retencion-irpf-factura", "verifactu-en-clientlabs", "migrar-de-excel-a-clientlabs", "pipeline-de-clientlabs"],
  },
  {
    slug: "pipeline-de-clientlabs",
    title: "Del primer contacto al cliente: el pipeline de ClientLabs",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "4 min",
    publishedAt: "2026-02-25",
    description: "Cómo funciona el pipeline de ClientLabs: del lead al cliente con estados, seguimiento y la factura conectada, sin teclear los mismos datos dos veces.",
    tags: ["pipeline ClientLabs", "autónomos"],
    relatedSlugs: ["sistema-de-leads-simple", "que-es-un-crm", "primera-factura-clientlabs", "clientes-y-proveedores-centralizados", "conseguir-clientes-por-internet"],
  },
  {
    slug: "verifactu-en-clientlabs",
    title: "Verifactu en ClientLabs: QR, huella y envío a Hacienda sin tocar nada",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "4 min",
    publishedAt: "2026-02-20",
    description: "Cómo ClientLabs cumple Verifactu: cada factura con huella, encadenamiento, QR y leyenda, y el envío a Hacienda automático, sin configurar nada técnico.",
    tags: ["Verifactu ClientLabs", "autónomos"],
    relatedSlugs: ["verifactu-2026", "primera-factura-clientlabs", "factura-electronica-obligatoria", "errores-factura-autonomo", "mejores-programas-facturacion-autonomos-2026"],
  },
  {
    slug: "migrar-de-excel-a-clientlabs",
    title: "Migra de Excel a ClientLabs: clientes, facturas y datos en 10 min",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "4 min",
    publishedAt: "2026-02-15",
    description: "Cómo migrar de Excel a ClientLabs en 10 minutos: exporta tus clientes y facturas, impórtalos y configura tus datos fiscales. Sin perder histórico.",
    tags: ["migrar de Excel a ClientLabs", "autónomos"],
    relatedSlugs: ["facturar-en-excel-2026", "primera-factura-clientlabs", "clientes-y-proveedores-centralizados", "verifactu-en-clientlabs", "alternativas-facturaplus"],
  },
  {
    slug: "gastos-deducibles-autonomo-2026",
    title: "Gastos deducibles del autónomo en 2026: la lista con ejemplos",
    category: "Guía",
    categoryKey: "guia",
    categoryColor: "bg-emerald-50 text-emerald-700",
    readTime: "5 min",
    publishedAt: "2026-06-19",
    description: "Lista de gastos deducibles del autónomo en 2026 por categorías, con ejemplos y los 3 requisitos que exige Hacienda para que un gasto cuente.",
    tags: ["gastos deducibles autónomo", "autónomos", "2026"],
    relatedSlugs: ["modelo-303", "modelo-130", "calendario-fiscal-autonomo-2026", "cuota-autonomos-2026", "como-hacer-una-factura"],
  },
  {
    slug: "como-hacer-una-factura",
    title: "Cómo hacer una factura: partes obligatorias y plantilla gratis",
    category: "Guía",
    categoryKey: "guia",
    categoryColor: "bg-emerald-50 text-emerald-700",
    readTime: "4 min",
    publishedAt: "2026-06-19",
    description: "Cómo hacer una factura correcta en 2026: todas las partes obligatorias, tipos de factura y una plantilla gratis lista para descargar y usar.",
    tags: ["cómo hacer una factura", "autónomos"],
    relatedSlugs: ["verifactu-2026", "retencion-irpf-factura", "errores-factura-autonomo", "gastos-deducibles-autonomo-2026", "primera-factura-clientlabs"],
  },
  {
    slug: "darse-de-alta-como-autonomo-2026",
    title: "Cómo darte de alta como autónomo en 2026 (Hacienda y SS)",
    category: "Guía",
    categoryKey: "guia",
    categoryColor: "bg-emerald-50 text-emerald-700",
    readTime: "4 min",
    publishedAt: "2026-06-19",
    description: "Cómo darse de alta como autónomo en 2026: alta en Hacienda (036/037) y en la Seguridad Social (RETA), plazos, tarifa plana y documentación.",
    tags: ["darse de alta como autónomo", "autónomos", "2026"],
    relatedSlugs: ["cuota-autonomos-2026", "calendario-fiscal-autonomo-2026", "gastos-deducibles-autonomo-2026", "como-hacer-una-factura", "modelo-130"],
  },
  {
    slug: "kit-digital-2026",
    title: "Kit Digital 2026: cómo conseguir la ayuda para digitalizar tu negocio",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "4 min",
    publishedAt: "2026-06-19",
    description: "Kit Digital 2026: qué es el bono de digitalización, quién puede pedirlo, en qué se gasta y cómo solicitarlo paso a paso a través de un agente digitalizador.",
    tags: ["kit digital 2026", "autónomos", "2026"],
    relatedSlugs: ["que-es-un-crm", "verifactu-2026", "mejores-programas-facturacion-autonomos-2026", "conseguir-clientes-por-internet", "migrar-de-excel-a-clientlabs"],
  },
  {
    slug: "retencion-irpf-factura",
    title: "Qué retención de IRPF pongo en mis facturas: 15 %, 7 % y excepciones",
    category: "Guía",
    categoryKey: "guia",
    categoryColor: "bg-emerald-50 text-emerald-700",
    readTime: "4 min",
    publishedAt: "2026-06-19",
    description: "Qué retención de IRPF poner en tus facturas: 15 % general, 7 % para nuevos autónomos y cuándo no se aplica. Con ejemplo de cálculo y FAQ.",
    tags: ["retención IRPF factura autónomo", "autónomos"],
    relatedSlugs: ["modelo-130", "como-hacer-una-factura", "modelo-303", "gastos-deducibles-autonomo-2026", "calendario-fiscal-autonomo-2026"],
  },
  {
    slug: "modelo-130",
    title: "Modelo 130 de IRPF: qué es, quién lo presenta y cómo se calcula",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "4 min",
    publishedAt: "2026-06-19",
    description: "Modelo 130 de IRPF: qué es, quién está obligado, cómo se calcula el pago fraccionado del 20 % y cuándo estás exento. Con ejemplo y plazos 2026.",
    tags: ["modelo 130", "autónomos"],
    relatedSlugs: ["modelo-303", "retencion-irpf-factura", "gastos-deducibles-autonomo-2026", "calendario-fiscal-autonomo-2026", "cuota-autonomos-2026"],
  },
]
