export type ArticleMeta = {
  slug: string
  title: string
  category: string
  categoryKey: "normativa" | "guia" | "comparativa" | "tutorial" | "negocio"
  categoryColor: string
  readTime: string
  publishedAt: string
  description: string
  tags: string[]
  relatedSlugs: string[]
}

export const ARTICLES: ArticleMeta[] = [
  // ─── TOFU: Normativa ───────────────────────────────────────────────────────
  {
    slug: "verifactu-guia-completa",
    title: "Verifactu 2026: guía completa para autónomos y pymes",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "10 min",
    publishedAt: "2026-05-01",
    description: "Todo lo que necesitas saber sobre Verifactu: fechas de obligatoriedad, requisitos técnicos, sanciones y cómo prepararte como autónomo o pyme española.",
    tags: ["verifactu", "facturación electrónica", "AEAT", "autónomos", "normativa fiscal"],
    relatedSlugs: ["facturacion-electronica-obligatoria-espana", "errores-facturacion-autonomos", "clientlabs-verifactu-facturacion-legal"],
  },
  {
    slug: "facturacion-electronica-obligatoria-espana",
    title: "Facturación electrónica obligatoria en España: todo lo que necesitas saber en 2026",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "9 min",
    publishedAt: "2026-05-02",
    description: "La Ley Crea y Crece hace obligatoria la facturación electrónica en España. Descubre quién está afectado, desde cuándo y cómo adaptarte sin complicaciones.",
    tags: ["facturación electrónica", "Ley Crea y Crece", "España", "autónomos", "pymes"],
    relatedSlugs: ["verifactu-guia-completa", "errores-facturacion-autonomos", "crear-primera-factura-clientlabs"],
  },
  {
    slug: "errores-facturacion-autonomos",
    title: "Los 10 errores más comunes en la facturación de autónomos (y cómo evitarlos)",
    category: "Guía",
    categoryKey: "guia",
    categoryColor: "bg-emerald-50 text-emerald-700",
    readTime: "8 min",
    publishedAt: "2026-04-28",
    description: "Descubre los 10 errores de facturación que más multas y problemas generan a los autónomos españoles y aprende cómo evitarlos fácilmente.",
    tags: ["facturación", "errores", "autónomos", "IVA", "IRPF", "sanciones AEAT"],
    relatedSlugs: ["verifactu-guia-completa", "modelo-303-iva-trimestral-guia", "crear-primera-factura-clientlabs"],
  },
  {
    slug: "modelo-303-iva-trimestral-guia",
    title: "Modelo 303 IVA trimestral: guía paso a paso para autónomos 2026",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "10 min",
    publishedAt: "2026-04-25",
    description: "Guía completa para rellenar el Modelo 303 sin errores: plazos, casillas, cálculo de IVA repercutido e IVA soportado, y cómo presentarlo en la Sede Electrónica.",
    tags: ["modelo 303", "IVA", "trimestral", "autónomos", "hacienda", "AEAT"],
    relatedSlugs: ["obligaciones-fiscales-autonomo-2026", "errores-facturacion-autonomos", "cuota-autonomos-2026"],
  },
  {
    slug: "cuota-autonomos-2026",
    title: "Cuota de autónomos 2026: tarifa plana, tramos y todo lo que cambia",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "9 min",
    publishedAt: "2026-04-20",
    description: "Todo sobre la cuota de autónomos en 2026: el nuevo sistema de cotización por ingresos reales, los 15 tramos, la tarifa plana y cómo reducir legalmente lo que pagas.",
    tags: ["cuota autónomos", "tarifa plana", "RETA", "2026", "seguridad social", "ingresos reales"],
    relatedSlugs: ["obligaciones-fiscales-autonomo-2026", "modelo-303-iva-trimestral-guia", "errores-facturacion-autonomos"],
  },
  // ─── TOFU: Negocio y Gestión ──────────────────────────────────────────────
  {
    slug: "como-gestionar-leads-autonomo",
    title: "Cómo gestionar leads si eres autónomo sin perder oportunidades",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "8 min",
    publishedAt: "2026-04-18",
    description: "Sistema práctico para gestionar leads como autónomo: desde el primer contacto hasta el cierre. Métricas clave, herramientas y automatizaciones.",
    tags: ["leads", "gestión", "autónomos", "CRM", "pipeline", "conversión"],
    relatedSlugs: ["que-es-crm-autonomos", "gestionar-leads-clientlabs", "captar-clientes-internet-autonomo"],
  },
  {
    slug: "organizar-clientes-proveedores",
    title: "Cómo organizar clientes y proveedores sin volverse loco",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "7 min",
    publishedAt: "2026-04-15",
    description: "Centraliza toda la información de clientes y proveedores: datos fiscales, historial de facturas, contactos y notas en un solo lugar.",
    tags: ["clientes", "proveedores", "organización", "CRM", "autónomos", "modelo 347"],
    relatedSlugs: ["que-es-crm-autonomos", "como-gestionar-leads-autonomo", "errores-facturacion-autonomos"],
  },
  {
    slug: "que-es-crm-autonomos",
    title: "Qué es un CRM y por qué todo autónomo necesita uno",
    category: "Guía",
    categoryKey: "guia",
    categoryColor: "bg-emerald-50 text-emerald-700",
    readTime: "8 min",
    publishedAt: "2026-04-10",
    description: "Explicación clara de qué es un CRM, para qué sirve y por qué cada autónomo necesita uno para gestionar clientes, leads y facturación de forma organizada.",
    tags: ["CRM", "autónomos", "gestión clientes", "software", "pymes", "ROI"],
    relatedSlugs: ["mejor-crm-gratis-autonomos", "como-gestionar-leads-autonomo", "migrar-excel-clientlabs"],
  },
  {
    slug: "captar-clientes-internet-autonomo",
    title: "Cómo captar clientes en internet siendo autónomo en España",
    category: "Negocio",
    categoryKey: "negocio",
    categoryColor: "bg-pink-50 text-pink-700",
    readTime: "9 min",
    publishedAt: "2026-04-05",
    description: "Estrategias reales para captar clientes en internet como autónomo español: SEO local, Google My Business, LinkedIn, contenido y captación automática.",
    tags: ["captar clientes", "marketing digital", "autónomos", "leads", "SEO", "Google My Business"],
    relatedSlugs: ["como-gestionar-leads-autonomo", "gestionar-leads-clientlabs", "que-es-crm-autonomos"],
  },
  {
    slug: "obligaciones-fiscales-autonomo-2026",
    title: "Obligaciones fiscales del autónomo en 2026: calendario completo",
    category: "Normativa",
    categoryKey: "normativa",
    categoryColor: "bg-amber-50 text-amber-700",
    readTime: "10 min",
    publishedAt: "2026-04-01",
    description: "Todas las obligaciones fiscales del autónomo en 2026 con fechas exactas: modelos 303, 130, 347, 390, declaración de la renta y consecuencias de no cumplir.",
    tags: ["obligaciones fiscales", "autónomos", "hacienda", "modelos tributarios", "calendario fiscal"],
    relatedSlugs: ["modelo-303-iva-trimestral-guia", "cuota-autonomos-2026", "errores-facturacion-autonomos"],
  },
  // ─── MOFU: Comparativas ────────────────────────────────────────────────────
  {
    slug: "mejores-software-facturacion-autonomos",
    title: "Los 10 mejores software de facturación para autónomos en España 2026",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "12 min",
    publishedAt: "2026-03-28",
    description: "Comparativa de los 10 mejores programas de facturación para autónomos en España: precios, funciones clave, Verifactu y para quién es cada uno.",
    tags: ["software facturación", "comparativa", "autónomos", "España", "2026", "Verifactu"],
    relatedSlugs: ["clientlabs-vs-holded", "clientlabs-vs-quipu", "facturar-excel-vs-software"],
  },
  {
    slug: "clientlabs-vs-holded",
    title: "ClientLabs vs Holded: comparativa completa para autónomos 2026",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "10 min",
    publishedAt: "2026-03-25",
    description: "Comparativa honesta entre ClientLabs y Holded: precios, funciones, CRM, facturación y para qué perfil de negocio es mejor cada uno en 2026.",
    tags: ["ClientLabs", "Holded", "comparativa", "facturación", "CRM", "autónomos"],
    relatedSlugs: ["mejores-software-facturacion-autonomos", "clientlabs-vs-quipu", "mejor-crm-gratis-autonomos"],
  },
  {
    slug: "clientlabs-vs-quipu",
    title: "ClientLabs vs Quipu: ¿cuál es mejor para tu negocio?",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "9 min",
    publishedAt: "2026-03-20",
    description: "Comparativa detallada de ClientLabs y Quipu en facturación, contabilidad, gestión de clientes, precio y soporte para autónomos.",
    tags: ["ClientLabs", "Quipu", "comparativa", "facturación", "contabilidad", "autónomos"],
    relatedSlugs: ["mejores-software-facturacion-autonomos", "clientlabs-vs-holded", "alternativas-facturaplus"],
  },
  {
    slug: "alternativas-facturaplus",
    title: "Alternativas a FacturaPlus para autónomos en 2026",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "9 min",
    publishedAt: "2026-03-15",
    description: "FacturaPlus se ha quedado obsoleto. Descubre las 6 mejores alternativas modernas con Verifactu, cloud y precios más justos para autónomos en 2026.",
    tags: ["FacturaPlus", "alternativas", "facturación", "software", "autónomos", "migración"],
    relatedSlugs: ["mejores-software-facturacion-autonomos", "migrar-excel-clientlabs", "facturar-excel-vs-software"],
  },
  {
    slug: "mejor-crm-gratis-autonomos",
    title: "Mejor CRM gratis para autónomos y pymes en España",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "9 min",
    publishedAt: "2026-03-10",
    description: "Los 7 mejores CRM con plan gratuito para autónomos y pymes españoles: qué incluye cada plan gratis, sus limitaciones y cuándo necesitas pasarte al de pago.",
    tags: ["CRM gratis", "autónomos", "pymes", "España", "software", "HubSpot", "Zoho"],
    relatedSlugs: ["que-es-crm-autonomos", "clientlabs-vs-holded", "migrar-excel-clientlabs"],
  },
  {
    slug: "facturar-excel-vs-software",
    title: "Facturar con Excel vs usar un software profesional: la comparativa definitiva",
    category: "Comparativa",
    categoryKey: "comparativa",
    categoryColor: "bg-blue-50 text-blue-700",
    readTime: "8 min",
    publishedAt: "2026-03-05",
    description: "¿Sigue valiendo la pena facturar con Excel en 2026? Comparativa real en tiempo, errores, coste y cumplimiento normativo (Verifactu) frente a software profesional.",
    tags: ["Excel", "facturación", "software", "comparativa", "autónomos", "Verifactu"],
    relatedSlugs: ["mejores-software-facturacion-autonomos", "migrar-excel-clientlabs", "errores-facturacion-autonomos"],
  },
  // ─── BOFU: Tutoriales ──────────────────────────────────────────────────────
  {
    slug: "crear-primera-factura-clientlabs",
    title: "Cómo crear tu primera factura legal con ClientLabs (tutorial paso a paso)",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "8 min",
    publishedAt: "2026-03-01",
    description: "Tutorial completo para crear tu primera factura legal con ClientLabs: configuración inicial, cliente, IVA, IRPF, envío al cliente y registro del cobro.",
    tags: ["ClientLabs", "tutorial", "factura", "Verifactu", "paso a paso", "autónomos"],
    relatedSlugs: ["errores-facturacion-autonomos", "clientlabs-verifactu-facturacion-legal", "migrar-excel-clientlabs"],
  },
  {
    slug: "gestionar-leads-clientlabs",
    title: "Cómo gestionar leads y convertirlos en clientes con ClientLabs",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "9 min",
    publishedAt: "2026-02-25",
    description: "Tutorial completo del pipeline de leads de ClientLabs: captura automática, seguimiento, puntuación, conversión a cliente y automatizaciones de email.",
    tags: ["leads", "clientes", "conversión", "ClientLabs", "CRM", "pipeline", "tutorial"],
    relatedSlugs: ["como-gestionar-leads-autonomo", "captar-clientes-internet-autonomo", "crear-primera-factura-clientlabs"],
  },
  {
    slug: "clientlabs-verifactu-facturacion-legal",
    title: "ClientLabs + Verifactu: facturación legal automática para autónomos",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "8 min",
    publishedAt: "2026-02-20",
    description: "Cómo funciona Verifactu en ClientLabs: hash SHA-256 automático, código QR en cada factura y envío en tiempo real a la AEAT. Sin tecnicismos.",
    tags: ["ClientLabs", "Verifactu", "facturación legal", "AEAT", "QR", "hash SHA-256"],
    relatedSlugs: ["verifactu-guia-completa", "crear-primera-factura-clientlabs", "facturacion-electronica-obligatoria-espana"],
  },
  {
    slug: "migrar-excel-clientlabs",
    title: "De Excel a ClientLabs: cómo migrar tu facturación en 10 minutos",
    category: "Tutorial",
    categoryKey: "tutorial",
    categoryColor: "bg-violet-50 text-violet-700",
    readTime: "7 min",
    publishedAt: "2026-02-15",
    description: "Guía paso a paso para migrar tu facturación de Excel a ClientLabs: exportar clientes, importar datos, configurar datos fiscales y empezar a facturar.",
    tags: ["migrar", "Excel", "ClientLabs", "facturación", "tutorial", "importar clientes"],
    relatedSlugs: ["facturar-excel-vs-software", "crear-primera-factura-clientlabs", "que-es-crm-autonomos"],
  },
]
