export type ArticleMeta = {
  slug: string
  title: string
  category: string
  categoryColor: string
  readTime: string
  date: string
  excerpt: string
  description: string
  relatedSlugs: string[]
}

export const ARTICLES: ArticleMeta[] = [
  {
    slug: "como-no-perder-clientes-seguimiento",
    title: "Cómo no perder clientes por no hacer seguimiento",
    category: "Gestión de clientes",
    categoryColor: "bg-[#E1F5EE] text-[#1FA97A]",
    readTime: "5 min",
    date: "1 de abril de 2026",
    excerpt: "El error más común de los autónomos es conseguir un cliente potencial y luego olvidarse de él. Te explicamos cómo evitarlo.",
    description: "Descubre cómo implementar un sistema de seguimiento de clientes efectivo como autónomo. Nunca más pierdas un lead por no hacer seguimiento.",
    relatedSlugs: ["crm-para-autonomos-guia-completa", "seguimiento-clientes-autonomo"],
  },
  {
    slug: "facturacion-autonomos-espana-2026",
    title: "Facturación para autónomos en España en 2026: todo lo que necesitas saber",
    category: "Fiscalidad",
    categoryColor: "bg-blue-50 text-blue-600",
    readTime: "8 min",
    date: "25 de marzo de 2026",
    excerpt: "IVA, IRPF, Verifactu, franquicia de IVA... La normativa fiscal para autónomos cambia cada año. Aquí tienes todo actualizado.",
    description: "Todo sobre facturación para autónomos en España en 2026: Verifactu, IVA, IRPF, modelos tributarios y cumplimiento con la AEAT.",
    relatedSlugs: ["factura-electronica-autonomos-2026", "modelo-303-autonomos-guia"],
  },
  {
    slug: "herramientas-gestion-autonomos",
    title: "Las 5 herramientas que todo autónomo necesita en 2026",
    category: "Productividad",
    categoryColor: "bg-purple-50 text-purple-600",
    readTime: "6 min",
    date: "15 de marzo de 2026",
    excerpt: "Desde el CRM hasta la facturación, estas son las herramientas que te van a ahorrar más tiempo cada semana.",
    description: "Las 5 categorías de herramientas indispensables para autónomos en 2026: CRM, facturación, proyectos, comunicación y contabilidad.",
    relatedSlugs: ["herramientas-productividad-autonomos-2026", "como-automatizar-negocio-autonomo"],
  },
  {
    slug: "como-conseguir-primeros-clientes",
    title: "Cómo conseguir tus primeros 10 clientes como autónomo",
    category: "Captación",
    categoryColor: "bg-orange-50 text-orange-600",
    readTime: "7 min",
    date: "5 de marzo de 2026",
    excerpt: "La guía práctica que nadie te da cuando empiezas. Sin teoría, sin humo. Solo lo que realmente funciona.",
    description: "Estrategias probadas para conseguir tus primeros clientes como autónomo: red de contactos, propuesta de valor, LinkedIn y referencias.",
    relatedSlugs: ["como-conseguir-clientes-autonomo-sin-publicidad", "alta-autonomo-paso-a-paso"],
  },
  {
    slug: "como-gestionar-tiempo-autonomo",
    title: "Gestión del tiempo para autónomos: cómo trabajar menos y ganar más",
    category: "Productividad",
    categoryColor: "bg-purple-50 text-purple-600",
    readTime: "6 min",
    date: "8 de abril de 2026",
    excerpt: "Las técnicas de gestión del tiempo más efectivas para autónomos. Trabaja de forma más inteligente y aumenta tus ingresos.",
    description: "Descubre las técnicas de gestión del tiempo más efectivas para autónomos. Trabaja de forma más inteligente y aumenta tus ingresos sin aumentar tus horas.",
    relatedSlugs: ["herramientas-productividad-autonomos-2026", "como-automatizar-negocio-autonomo"],
  },
  {
    slug: "errores-fiscales-autonomos-espana",
    title: "Los 7 errores fiscales más comunes de los autónomos en España (y cómo evitarlos)",
    category: "Fiscalidad",
    categoryColor: "bg-blue-50 text-blue-600",
    readTime: "7 min",
    date: "5 de abril de 2026",
    excerpt: "Los errores fiscales que más dinero le cuestan a los autónomos españoles y cómo evitarlos para no tener problemas con Hacienda.",
    description: "Conoce los errores fiscales que más dinero le cuestan a los autónomos españoles y aprende cómo evitarlos para no tener problemas con Hacienda.",
    relatedSlugs: ["facturacion-autonomos-espana-2026", "modelo-303-autonomos-guia"],
  },
  {
    slug: "como-fijar-precios-servicios-autonomo",
    title: "Cómo fijar el precio de tus servicios como autónomo sin quedarte corto",
    category: "Negocio",
    categoryColor: "bg-amber-50 text-amber-600",
    readTime: "7 min",
    date: "3 de abril de 2026",
    excerpt: "Métodos probados para calcular y fijar el precio correcto para tus servicios como autónomo. Valora tu trabajo correctamente.",
    description: "Aprende a calcular y fijar el precio correcto para tus servicios como autónomo. Métodos probados para valorar tu trabajo correctamente.",
    relatedSlugs: ["como-crear-presupuesto-profesional", "autonomo-o-sociedad-limitada"],
  },
  {
    slug: "crm-para-autonomos-guia-completa",
    title: "CRM para autónomos: la guía completa para elegir el mejor",
    category: "Herramientas",
    categoryColor: "bg-indigo-50 text-indigo-600",
    readTime: "8 min",
    date: "1 de abril de 2026",
    excerpt: "Todo lo que necesitas saber para elegir el mejor CRM como autónomo. Comparativa y funcionalidades clave.",
    description: "Todo lo que necesitas saber para elegir el mejor CRM como autónomo. Comparativa, funcionalidades clave y por qué un CRM específico para autónomos marca la diferencia.",
    relatedSlugs: ["como-no-perder-clientes-seguimiento", "seguimiento-clientes-autonomo"],
  },
  {
    slug: "como-conseguir-clientes-autonomo-sin-publicidad",
    title: "Cómo conseguir clientes como autónomo sin gastar en publicidad",
    category: "Captación",
    categoryColor: "bg-orange-50 text-orange-600",
    readTime: "6 min",
    date: "28 de marzo de 2026",
    excerpt: "Estrategias comprobadas para conseguir clientes como autónomo sin invertir en publicidad. Networking, referencias, contenido y más.",
    description: "Estrategias comprobadas para conseguir clientes como autónomo sin invertir en publicidad. Networking, referencias, contenido y más.",
    relatedSlugs: ["como-conseguir-primeros-clientes", "como-retener-clientes-autonomo"],
  },
  {
    slug: "factura-electronica-autonomos-2026",
    title: "Factura electrónica para autónomos en 2026: todo lo que debes saber antes de que sea obligatoria",
    category: "Fiscalidad",
    categoryColor: "bg-blue-50 text-blue-600",
    readTime: "8 min",
    date: "26 de marzo de 2026",
    excerpt: "La factura electrónica será obligatoria para autónomos en España. Descubre qué es Verifactu, cuándo entra en vigor y cómo prepararte.",
    description: "La factura electrónica será obligatoria para autónomos en España. Descubre qué es Verifactu, cuándo entra en vigor y cómo prepararte.",
    relatedSlugs: ["facturacion-autonomos-espana-2026", "errores-fiscales-autonomos-espana"],
  },
  {
    slug: "como-retener-clientes-autonomo",
    title: "Cómo retener a tus clientes como autónomo: 8 estrategias que funcionan",
    category: "Gestión de clientes",
    categoryColor: "bg-[#E1F5EE] text-[#1FA97A]",
    readTime: "6 min",
    date: "24 de marzo de 2026",
    excerpt: "Retener un cliente es mucho más rentable que conseguir uno nuevo. 8 estrategias probadas para fidelizar clientes como autónomo.",
    description: "Retener un cliente es mucho más rentable que conseguir uno nuevo. Descubre 8 estrategias probadas para fidelizar clientes como autónomo.",
    relatedSlugs: ["como-no-perder-clientes-seguimiento", "seguimiento-clientes-autonomo"],
  },
  {
    slug: "herramientas-productividad-autonomos-2026",
    title: "Las mejores herramientas de productividad para autónomos en 2026",
    category: "Productividad",
    categoryColor: "bg-purple-50 text-purple-600",
    readTime: "7 min",
    date: "22 de marzo de 2026",
    excerpt: "Selección de las mejores herramientas para autónomos en 2026: gestión de proyectos, comunicación, facturación y automatización.",
    description: "Selección de las mejores herramientas para autónomos en 2026: gestión de proyectos, comunicación, facturación y automatización.",
    relatedSlugs: ["herramientas-gestion-autonomos", "como-automatizar-negocio-autonomo"],
  },
  {
    slug: "modelo-303-autonomos-guia",
    title: "Modelo 303: guía paso a paso para autónomos que declaran el IVA por primera vez",
    category: "Fiscalidad",
    categoryColor: "bg-blue-50 text-blue-600",
    readTime: "8 min",
    date: "20 de marzo de 2026",
    excerpt: "Guía completa para rellenar el Modelo 303 como autónomo. Declara el IVA trimestral paso a paso sin cometer errores.",
    description: "Guía completa para rellenar el Modelo 303 como autónomo. Aprende a declarar el IVA trimestral paso a paso sin cometer errores.",
    relatedSlugs: ["facturacion-autonomos-espana-2026", "errores-fiscales-autonomos-espana"],
  },
  {
    slug: "como-crear-presupuesto-profesional",
    title: "Cómo crear un presupuesto profesional que consiga más clientes",
    category: "Negocio",
    categoryColor: "bg-amber-50 text-amber-600",
    readTime: "5 min",
    date: "18 de marzo de 2026",
    excerpt: "Aprende a crear presupuestos profesionales que conviertan. Estructura, presentación y los elementos que marcan la diferencia.",
    description: "Aprende a crear presupuestos profesionales que conviertan. Estructura, presentación y los elementos que marcan la diferencia.",
    relatedSlugs: ["como-fijar-precios-servicios-autonomo", "como-conseguir-primeros-clientes"],
  },
  {
    slug: "autonomo-o-sociedad-limitada",
    title: "Autónomo o Sociedad Limitada: ¿cuándo te compensa el cambio?",
    category: "Fiscalidad",
    categoryColor: "bg-blue-50 text-blue-600",
    readTime: "9 min",
    date: "17 de marzo de 2026",
    excerpt: "¿Deberías montar una Sociedad Limitada? Analizamos cuándo compensa el cambio según tus ingresos y situación fiscal.",
    description: "¿Deberías montar una Sociedad Limitada? Analizamos cuándo compensa el cambio de autónomo a SL según tus ingresos y situación fiscal.",
    relatedSlugs: ["errores-fiscales-autonomos-espana", "cuota-autonomos-2026"],
  },
  {
    slug: "como-automatizar-negocio-autonomo",
    title: "Cómo automatizar tu negocio como autónomo para trabajar menos",
    category: "Productividad",
    categoryColor: "bg-purple-50 text-purple-600",
    readTime: "6 min",
    date: "12 de marzo de 2026",
    excerpt: "Automatiza las tareas repetitivas de tu negocio como autónomo. Más tiempo para lo que importa, menos tareas manuales.",
    description: "Descubre cómo automatizar las tareas repetitivas de tu negocio como autónomo. Más tiempo para lo que importa, menos tareas manuales.",
    relatedSlugs: ["herramientas-productividad-autonomos-2026", "herramientas-gestion-autonomos"],
  },
  {
    slug: "seguimiento-clientes-autonomo",
    title: "Seguimiento de clientes para autónomos: el sistema que evita que pierdas proyectos",
    category: "Gestión de clientes",
    categoryColor: "bg-[#E1F5EE] text-[#1FA97A]",
    readTime: "5 min",
    date: "10 de marzo de 2026",
    excerpt: "Sistema de seguimiento de clientes diseñado para autónomos. Cómo nunca perder un proyecto por falta de seguimiento.",
    description: "Sistema de seguimiento de clientes diseñado para autónomos. Cómo nunca perder un proyecto por falta de seguimiento.",
    relatedSlugs: ["como-no-perder-clientes-seguimiento", "crm-para-autonomos-guia-completa"],
  },
  {
    slug: "cuota-autonomos-2026",
    title: "Cuota de autónomos en 2026: cuánto pagas y cómo reducirla legalmente",
    category: "Fiscalidad",
    categoryColor: "bg-blue-50 text-blue-600",
    readTime: "7 min",
    date: "8 de marzo de 2026",
    excerpt: "Todo sobre la cuota de autónomos en 2026. Tramos, exenciones, tarifa plana y formas legales de reducir lo que pagas.",
    description: "Todo sobre la cuota de autónomos en 2026. Tramos, exenciones, tarifa plana y formas legales de reducir lo que pagas a la Seguridad Social.",
    relatedSlugs: ["autonomo-o-sociedad-limitada", "alta-autonomo-paso-a-paso"],
  },
  {
    slug: "como-organizar-finanzas-autonomo",
    title: "Cómo organizar las finanzas de tu negocio como autónomo desde cero",
    category: "Finanzas",
    categoryColor: "bg-teal-50 text-teal-600",
    readTime: "7 min",
    date: "7 de marzo de 2026",
    excerpt: "Guía práctica para organizar las finanzas de tu negocio como autónomo. Separar cuentas, provisionar impuestos y llevar el control.",
    description: "Guía práctica para organizar las finanzas de tu negocio como autónomo. Separar cuentas, provisionar impuestos y llevar el control.",
    relatedSlugs: ["errores-fiscales-autonomos-espana", "cuota-autonomos-2026"],
  },
  {
    slug: "alta-autonomo-paso-a-paso",
    title: "Cómo darse de alta como autónomo en España en 2026: guía paso a paso",
    category: "Emprender",
    categoryColor: "bg-rose-50 text-rose-600",
    readTime: "8 min",
    date: "5 de marzo de 2026",
    excerpt: "Guía completa para darse de alta como autónomo en España en 2026. Pasos, trámites, costes y consejos para el primer año.",
    description: "Guía completa para darse de alta como autónomo en España en 2026. Pasos, trámites, costes y consejos para el primer año.",
    relatedSlugs: ["cuota-autonomos-2026", "como-conseguir-primeros-clientes"],
  },
]
