import { SectorConfig } from "./types";

/**
 * DEFAULT SECTOR CONFIGURATION
 * 
 * Esta es la configuración base que utiliza la aplicación actualmente.
 * Actúa como fallback y mantiene el comportamiento 100% idéntico al actual.
 */
export const defaultSectorConfig: SectorConfig = {
    id: 'default',
    name: 'General',
    description: 'Configuración estándar del sistema CRM.',

    routes: {
        base: '/dashboard',
        providers: '/dashboard/providers',
        clients: '/dashboard/other/clients',
        leads: '/dashboard/other/leads',
    },

    labels: {
        dashboard: {
            title: 'Resumen General',
            sections: {
                metrics: 'Métricas Principales',
                analysis: 'Análisis de Rendimiento',
                activity: 'Actividad y Inteligencia',
                ai: 'Inteligencia Artificial',
            },
            charts: {
                revenue: {
                    title: 'Evolución de Ingresos',
                    subtitle: 'Comparativa mensual vs objetivos',
                    series: {
                        income: 'Ingresos',
                        target: 'Objetivo',
                    }
                },
            funnel: {
                title: 'Embudo de Conversión',
                subtitle: 'Flujo de visitantes a ventas',
                quantityLabel: 'Cantidad',
                steps: {
                    visitors: 'Visitantes',
                    leads: 'Leads',
                    opportunities: 'Oportunidades',
                    sales: 'Ventas',
                }
            }
        },
        kpis: {
            incomeDescription: 'Mes actual',
            salesDescription: 'Este mes',
            clientsDescription: 'Total activos',
            leadsDescription: 'Esta semana',
            tasksDescription: 'Pendientes',
            botsTitle: 'Bots Activos',
            botsDescription: 'Automatizaciones',
        },
        widgets: {
            activityFeedTitle: 'Actividad Reciente',
            activityClientRegisteredDesc: 'María González se registró automáticamente',
            activitySaleCompletedDesc: 'Venta de €299 procesada exitosamente',
            activityAutomationRun: 'Automatización ejecutada',
            activityAutomationRunDesc: 'Email de seguimiento enviado a 5 clientes',
            activityTaskCompletedDesc: 'Llamada de seguimiento realizada',
            activityMessageSent: 'Mensaje enviado',
            activityMessageSentDesc: 'Notificación automática enviada',
            activitySystemAlert: 'Alerta de sistema',
            activitySystemAlertDesc: 'Stock bajo detectado automáticamente',
            quickActionsSuffix: 'Rápidas',
            quickActionsAvailable: 'disponibles',
            quickActionsCustomize: 'Personalizar acciones',
            newInvoice: 'Nueva Factura',
            newInvoiceDesc: 'Crear factura profesional',
            newAutomation: 'Nueva Automatización',
            newAutomationDesc: 'Crear flujo automático',
            viewAnalyticsDesc: 'Consultar métricas detalladas',
            createReport: 'Crear Reporte',
            createReportDesc: 'Generar reporte personalizado',
            systemStatusTitle: 'Estado del Sistema',
            systemStatusActiveServices: 'servicios activos',
            statusOnline: 'En línea',
            statusWarning: 'Advertencia',
            statusOffline: 'Fuera de línea',
            apiServer: 'API Server',
            database: 'Base de Datos',
            apiServerDesc: 'Respuesta en 45ms',
            databaseDesc: 'PostgreSQL activo',
            automationsStatusDesc: '12 bots activos',
            integrationsStatusDesc: '2 servicios con problemas',
            uptime: 'uptime',
            insightOpportunityTitle: 'Oportunidad de crecimiento',
            insightOpportunityMessage: 'Los clientes de Madrid representan el 40% de tus ingresos. Considera expandir tu presencia local.',
            insightClientRiskMessage: 'Empresa ABC no ha realizado compras en 30 días. Envía una oferta especial.',
            insightPatternTitle: 'Patrón detectado',
            insightPatternMessage: 'Las ventas aumentan un 25% los viernes. Optimiza tu estrategia de email marketing.',
            insightActionTitle: 'Acción recomendada',
            insightActionMessage: 'Automatiza el proceso de onboarding de nuevos clientes para reducir el tiempo de respuesta.',
        }
        },
        nav: {
            dashboard: 'Dashboard',
            providers: 'Proveedores',
            clients: 'Clientes',
            leads: 'Leads',
            tasks: 'Tareas',
            sales: 'Ventas',
            finance: 'Finanzas',
            billing: 'Facturación',
            analytics: 'Analytics',
            reporting: 'Reporte Ejecutivo',
            integrations: 'Integraciones',
            notifications: 'Notificaciones',
            settings: 'Ajustes',
        },
        providers: {
            title: 'Proveedores',
            singular: 'Proveedor',
            plural: 'Proveedores',
            newButton: 'Nuevo Proveedor',
            emptyState: 'No hay proveedores registrados',
            fields: {
                name: 'Nombre',
                type: 'Tipo',
                contactEmail: 'Email',
                contactPhone: 'Teléfono',
                website: 'Sitio Web',
                monthlyCost: 'Coste Mensual',
                dependencyLevel: 'Dependencia',
                status: 'Estado',
            },
            types: {
                SERVICE: 'Servicio',
                PRODUCT: 'Producto',
                SOFTWARE: 'Software',
                OTHER: 'Otro',
            },
            status: {
                ACTIVE: 'Activo',
                PAUSED: 'Pausado',
                BLOCKED: 'Bloqueado',
                OK: 'Estable',
                PENDING: 'Pendiente',
                ISSUE: 'Incidencia',
            },
            dependency: {
                LOW: 'Baja',
                MEDIUM: 'Media',
                HIGH: 'Alta',
                CRITICAL: 'Crítica',
            },
            actions: {
                newOrder: 'Nuevo Pedido',
                newTask: 'Nueva Tarea',
                addNote: 'Añadir Nota',
                uploadFile: 'Subir Archivo',
                markReceived: 'Marcar Recibido',
                markPaid: 'Marcar Pagado',
                cancel: 'Cancelar',
            }
        },
        clients: {
            title: 'Clientes',
            singular: 'Cliente',
            plural: 'Clientes',
            newButton: 'Nuevo Cliente',
            emptyState: 'No se encontraron clientes',
            status: {
                ACTIVE: 'Activo',
                FOLLOW_UP: 'Seguimiento',
                INACTIVE: 'Inactivo',
                VIP: 'VIP',
            }
        },
        leads: {
            title: 'Leads',
            singular: 'Lead',
            plural: 'Leads',
            newButton: 'Nuevo Lead',
            emptyState: 'No hay leads registrados',
            pageTitle: 'Pipeline de Oportunidades',
            pageSubtitle: 'Identifica, prioriza y convierte tus mejores leads en clientes',
            status: {
                NEW: 'Nuevo',
                CONTACTED: 'Contactado',
                INTERESTED: 'Interesado',
                QUALIFIED: 'Cualificado',
                PROPOSAL: 'Propuesta',
                NEGOTIATION: 'Negociación',
                CONVERTED: 'Convertido',
                LOST: 'Perdido',
            },
            temperatures: {
                HOT: 'Caliente',
                WARM: 'Templado',
                COLD: 'Frío',
            },
            actions: {
                registerCall: 'Llamada realizada',
                registerEmail: 'Email enviado',
                registerMeeting: 'Reunión realizada',
                convertToClient: 'Convertir a Cliente',
            },
            fields: {
                source: 'Fuente',
                created: 'Creado',
                lastAction: 'Última acción',
                score: 'Score',
            },
            ui: {
                emptyStateHint: 'Ajusta los filtros o comienza a capturar oportunidades',
                emptyStateImportCsv: 'Importar CSV',
                emptyStateImportCsvDesc: 'Carga masiva de leads',
                emptyStateConnectWeb: 'Conectar Web',
                emptyStateConnectWebDesc: 'Captura automática',
                emptyStateAutomate: 'Automatizar',
                emptyStateAutomateDesc: 'Flujos inteligentes',
                filterStatus: 'Estado',
                filterAll: 'Todos',
                filterTemperature: 'Temperatura',
                filterAllTemps: 'Todas',
                filterSource: 'Fuente',
                filterSourceAll: 'Todas',
                searchPlaceholder: 'Buscar por nombre, email o teléfono...',
                sortScoreDesc: 'Score ↓',
                sortScoreAsc: 'Score ↑',
                sortLastActionDesc: 'Contacto reciente',
                sortLastActionAsc: 'Contacto antiguo',
                sortCreatedDesc: 'Más nuevos',
                sortCreatedAsc: 'Más antiguos',
                sortTempHotFirst: 'HOT primero',
                showingResults: 'Mostrando',
                requireAttention: 'requieren atención inmediata',
                quickActions: 'Acciones Rápidas',
                addNote: 'Añadir nota',
                sendEmail: 'Enviar email',
                noEmail: 'Sin email',
                convertToClientShort: 'Convertir a cliente',
                markLostShort: 'Marcar perdido',
                changeStatus: 'Cambiar estado',
                markAs: 'Marcar como',
                deleteLead: 'Eliminar lead',
                viewClient: 'Ver Cliente',
                noteLabel: 'Nota',
                notePlaceholder: 'Escribe una nota...',
                reason: 'Razón',
                lostReasonPlaceholder: '¿Por qué se perdió este lead?',
                lostDialogTitle: 'Marcar como perdido',
                convertDialogTitle: '¿Convertir lead a cliente?',
                convertIrreversible: 'Esta acción es IRREVERSIBLE',
                convertBullet1: 'El lead quedará marcado como CONVERTIDO',
                convertBullet2: 'No podrás modificar su información',
                convertBullet3: 'Se creará o vinculará a un cliente',
                confirmConvert: 'Confirmar Conversión',
                toastNoteSaved: 'Nota guardada correctamente',
                toastErrorNote: 'Error al guardar nota',
                toastErrorStatus: 'Error al cambiar estado',
                toastDeleted: 'Lead eliminado correctamente',
                toastErrorDelete: 'Error al eliminar lead',
                deleteDialogTitle: '¿Eliminar lead?',
                deleteDialogDescription: 'Esta acción no se puede deshacer',
                deleteDialogConfirm: 'Estás a punto de eliminar permanentemente el lead:',
                deleteDialogWarning: 'Todos los datos asociados (notas, actividades, tags) serán eliminados.',
                deleteButton: 'Eliminar Lead',
                deleteButtonLoading: 'Eliminando...',
                toastMarkedLost: 'Lead marcado como perdido',
                toastConverted: 'Lead convertido a cliente',
                toastConvertedLinked: 'Lead convertido y vinculado a cliente existente',
                toastErrorConvert: 'Error al convertir lead',
                toastTagAdded: 'Tag añadido',
                toastTagRemoved: 'Tag eliminado',
                toastTagError: 'Error al añadir tag',
                toastReminderAdded: 'Recordatorio añadido',
                toastReminderError: 'Error al añadir recordatorio',
                toastReminderCompleted: 'Recordatorio completado',
                toastReminderCompleteError: 'Error al completar recordatorio',
                toastTempChanged: 'Temperatura cambiada a',
                toastTempChangeError: 'Error al cambiar temperatura',
                sidebarInfo: 'Información',
                sidebarSource: 'Fuente',
                sidebarCreated: 'Creado',
                sidebarLastAction: 'Última acción',
                sidebarScore: 'Score',
                sidebarTags: 'Tags',
                sidebarAddTag: 'Añadir tag',
                sidebarAddTagPlaceholder: 'Añadir tag...',
                sidebarTagsHint: 'Añade tags para organizar este lead',
                sidebarTagsReadOnly: 'Sin tags',
                sidebarNotes: 'Notas',
                sidebarNotesPlaceholder: 'Añadir o editar notas del lead...',
                sidebarSaveNote: 'Guardar nota',
                sidebarReadOnlyNote: 'Lead convertido o perdido - Solo lectura',
                sidebarReminders: 'Recordatorios',
                sidebarNoReminders: 'Sin recordatorios',
                sidebarAddReminder: 'Añadir recordatorio',
                reminderTypeCall: 'Llamar',
                reminderTypeEmail: 'Responder email',
                reminderTypeFollowUp: 'Seguimiento',
                reminderTypeCustom: 'Personalizado',
                reminderComplete: 'Completar',
                changeTemperature: 'Cambiar Temperatura',
                selectNewTemperature: 'Selecciona la nueva temperatura del lead:',
                closeButton: 'Cerrar',
                automationTitle: 'Automatización',
                automationComing: 'Próximamente: configuración avanzada',
                registerCallInNotes: 'Registra la llamada en las notas',
                registerFollowUpInNotes: 'Registra el seguimiento en las notas',
                leadConvertedOrLostReadOnly: 'No disponible para prospectos convertidos o perdidos',
                sidebarNoNotes: 'No hay notas para este lead',
                sidebarTasks: 'Tareas',
                sidebarAddTask: 'Añadir',
                sidebarNoTasks: 'No hay tareas pendientes',
                sidebarNextReminder: 'Próximo Recordatorio',
                reminderChange: 'Cambiar',
                createHowTitle: '¿Cómo quieres crear leads?',
                createManual: 'Manual',
                createManualDesc: 'Crear un lead manualmente',
                createImport: 'Importar Archivo',
                createImportDesc: 'CSV o Excel con múltiples leads',
                createPaste: 'Pegar Datos',
                createPasteDesc: 'Copy-paste masivo de texto',
                createScraping: 'Scraping por URL',
                createScrapingDesc: 'Extraer leads de una página web',
                badgeComing: 'Próximamente',
                daysNever: 'Nunca',
                daysToday: 'Hoy',
                daysYesterday: 'Ayer',
            }
        },
        tasks: {
            title: 'Tareas',
            singular: 'Tarea',
            plural: 'Tareas',
            newButton: 'Nueva Tarea',
            pageSubtitle: 'Gestiona tu día a día y seguimiento de clientes',
            status: {
                PENDING: 'Pendientes',
                IN_PROGRESS: 'En curso',
                DONE: 'Terminadas',
                CANCELLED: 'Canceladas',
            },
            priorities: {
                LOW: 'Baja',
                MEDIUM: 'Media',
                HIGH: 'Alta',
                URGENT: 'Urgente',
            },
            types: {
                MANUAL: 'Manual',
                CALL: 'Llamada',
                EMAIL: 'Email',
                MEETING: 'Reunión',
            },
            views: {
                today: 'Hoy',
                week: 'Esta semana',
                overdue: 'Vencidas',
                all: 'Todas',
                dayPlan: 'Día (ruta)',
                dashboard: 'Dashboard',
                calendar: 'Calendario',
            },
            ui: {
                loadingTasks: 'Cargando tareas...',
                emptyStateTitle: 'No hay tareas',
                emptyStateDescription: 'No tienes tareas pendientes en esta vista.',
                searchPlaceholder: 'Buscar tareas...',
                filterButton: 'Filtros',
                priorityHighBadge: 'Alta',
                overdueBadge: 'Vencida',
                noDate: 'Sin fecha',
                edit: 'Editar',
                delete: 'Eliminar',
                deleteDialogTitle: '¿Eliminar tarea?',
                deleteDialogDescription: 'Esta acción no se puede deshacer. La tarea será eliminada permanentemente.',
                toastErrorUpdate: 'Error al actualizar tarea',
                dialogTitleNew: 'Nueva Tarea',
                dialogTitleEdit: 'Editar Tarea',
                formTitle: 'Título',
                formTitlePlaceholder: 'Ej: Llamar a cliente...',
                formPriority: 'Prioridad',
                formType: 'Tipo',
                formDueDate: 'Fecha Vencimiento',
                cancel: 'Cancelar',
                saveChanges: 'Guardar Cambios',
                createTask: 'Crear Tarea',
                toastTitleRequired: 'El título es obligatorio',
                toastSaved: 'Tarea actualizada',
                toastCreated: 'Tarea creada',
                toastErrorSave: 'Error al guardar tarea',
                focusMode: 'Modo foco',
                visibleCount: 'visibles',
                productivitySection: 'Productividad',
            }
        },
        sales: {
            title: 'Ventas',
            singular: 'Venta',
            plural: 'Ventas',
            newButton: 'Nueva Venta',
            pageSubtitle: 'Registro manual y webhooks automáticos listos para escalar la operación.',
            stats: {
                totalRevenue: 'Ingresos Totales',
                growth: 'Crecimiento',
                avgTicket: 'Ticket Medio',
            },
            kpis: {
                factHoy: 'Facturación hoy',
                factMes: 'Facturación mes',
                ticketMedio: 'Ticket medio',
                ratioConversion: 'Ratio de conversión',
                hintHoy: 'Solo ventas con fecha actual',
                hintMes: 'Incluye webinars, inbound y pipeline',
                hintTicket: 'Promedio de importes activos',
                hintRatio: 'Ganadas ÷ total',
            },
            table: {
                pipelineTitle: 'Pipeline CRM',
                registerTitle: 'Registro de ventas',
                client: 'Cliente',
                product: 'Producto',
                amount: 'Importe',
                channel: 'Canal',
                commercial: 'Comercial',
                state: 'Estado',
                date: 'Fecha',
                origin: 'Origen',
            },
            status: {
                nueva: 'Nueva',
                seguimiento: 'Seguimiento',
                negociacion: 'Negociación',
                ganada: 'Ganada',
                perdida: 'Perdida',
            },
            paymentStatus: {
                PAGADO: 'Pagado',
                PAID: 'Pagado',
                PENDIENTE: 'Pendiente',
                PENDING: 'Pendiente',
                PARCIAL: 'Parcial',
                PARTIAL: 'Parcial',
                CANCELLED: 'Cancelado',
            },
            ui: {
                automationTitle: 'Automatizaciones',
                externalInputs: 'Entradas externas',
                webhooksHint: 'Implementaciones listas para los webhooks de Stripe y Shopify bajo',
                stateLabel: 'Estado',
                nextStepsTitle: 'Próximos pasos',
                createSale: 'Crear venta',
                manualRegister: 'Registro manual',
                saveSale: 'Guardar venta',
                saleSelected: 'Venta seleccionada',
                detail: 'Detalle',
                recentNotes: 'Notas recientes',
                originLabel: 'Origen',
                manualOrigin: 'Registro manual',
                webhookOrigin: 'Webhook automático',
                currentState: 'Estado actual',
                moveTo: 'Mover a',
            },
            timeRanges: {
                today: 'Hoy',
                last7: '7 días',
                last30: '30 días',
                month: 'Mes',
                last6months: '6 meses',
                year: 'Año',
                custom: 'Personalizado',
            },
            chartModes: {
                revenue: 'Ingresos',
                count: 'Nº ventas',
                avgTicket: 'Ticket medio',
            },
            insights: {
                vsPreviousPeriod: 'vs periodo anterior',
                topClient: 'Top cliente',
                paidShare: '% cobrado',
            },
            distribution: {
                byStatus: 'Por estado de pago',
                byClient: 'Por cliente',
            },
            heroChartTitle: 'Evolución',
            yoy: {
                title: 'Comparativa anual',
                chartTitle: 'Evolución comparada',
                noDataMessage: 'No hay datos suficientes del año anterior',
                tooltip: 'Comparación con el mismo periodo del año anterior',
                revenueLabel: 'Ingresos',
                salesLabel: 'Ventas',
                avgTicketLabel: 'Ticket medio',
                currentYear: 'Año actual',
                previousYear: 'Año anterior',
                newGrowth: 'Nuevo crecimiento',
            },
            forecast: {
                title: 'Forecast de ventas',
                chartRevenueTitle: 'Forecast de ingresos',
                chartSalesTitle: 'Forecast de ventas',
                noDataMessage: 'No hay suficientes datos para generar un forecast fiable',
                scenarios: { base: 'Base', conservador: 'Conservador', optimista: 'Optimista' },
                summaryNext30: 'Próximos 30 días',
                summaryNext90: 'Próximos 90 días',
                summaryEndOfMonth: 'Fin de mes',
                historical: 'Histórico',
                projected: 'Proyección',
            },
        },
        finance: {
            title: 'Finanzas',
            pageSubtitle: 'Gestiona tus ingresos y gastos',
            income: 'Ingresos',
            expenses: 'Gastos',
            netProfit: 'Beneficio Neto',
            burnRate: 'Burn Rate',
            cashFlow: 'Flujo de Caja',
            tabs: {
                overview: 'Vista General',
                transactions: 'Movimientos',
                budgets: 'Presupuestos',
                forecast: 'Pronóstico',
                goals: 'Objetivos',
                alerts: 'Alertas',
                automation: 'Automatización',
            }
        },
        billing: {
            title: 'Facturación',
            pageSubtitle: 'Gestiona tus facturas, pagos e integraciones con Hacienda',
            newInvoice: 'Nueva Factura',
            searchPlaceholder: 'Buscar facturas por cliente, número o descripción...',
        },
        analytics: {
            title: 'Analítica',
            pageTitle: 'Analítica avanzada',
            pageSubtitle: 'Métricas inteligentes y reportes ejecutivos para toma de decisiones',
            conversionRate: 'Tasa de Conversión',
            roi: 'ROI',
            performance: 'Rendimiento',
        },
        reporting: {
            title: 'Reporte Ejecutivo',
            pageSubtitle: 'Vista consolidada para toma de decisiones',
            kpis: {
                revenue: 'Ingresos',
                sales: 'Ventas',
                avgTicket: 'Ticket medio',
                growth: 'Crecimiento',
            },
            periods: {
                day: 'Hoy',
                last7: '7 días',
                last30: '30 días',
                last6m: '6 meses',
                last12m: '12 meses',
            },
            breakdown: {
                topClients: 'Top clientes',
                revenueByType: 'Ingresos por tipo',
            },
            insight: {
                title: 'Resumen ejecutivo',
            },
            chartTitle: 'Evolución de ingresos',
            forecast: {
                title: 'Previsión de ingresos',
                historical: 'Histórico',
                conservative: 'Conservador',
                realistic: 'Realista',
                optimistic: 'Optimista',
            },
            yoy: {
                title: 'Comparativa año contra año',
                currentYear: 'Año actual',
                previousYear: 'Año anterior',
                revenueYoY: 'Ingresos YoY',
                salesYoY: 'Ventas YoY',
                avgTicketYoY: 'Ticket medio YoY',
                periodYtd: 'Acumulado año',
                periodFullYear: 'Año completo',
            },
        },
        notifications: {
            title: 'Notificaciones',
            pageSubtitle: 'Mantente al día con tu negocio',
            markAllRead: 'Marcar todas como leídas',
        },
        aiAssistant: {
            title: 'Asistente IA',
            subtitle: 'Inteligencia artificial para tu negocio',
            pageSubtitle: 'Inteligencia artificial para optimizar tu negocio',
            insights: 'Insights',
            recommendations: 'Recomendaciones',
            predictions: 'Predicciones',
            newInsights: 'insights nuevos',
            precision: 'Precisión',
            lastUpdate: 'Última actualización',
            apply: 'Aplicar',
            ignore: 'Ignorar',
            viewFullAnalysis: 'Ver análisis completo',
            tabs: {
                overview: 'Vista General',
                insights: 'Insights IA',
                hotLeads: 'Leads Calientes',
                predictions: 'Predicciones',
                recommendations: 'Recomendaciones',
                automations: 'Automatizaciones',
                chat: 'Chat IA',
                timeline: 'Historial',
                settings: 'Configuración',
            }
        },
        integrations: {
            title: 'Integraciones',
            pageSubtitle: 'Conecta tus herramientas favoritas y automatiza procesos',
            connected: 'Conectadas',
            available: 'Disponibles',
            tabs: {
                overview: 'Vista General',
                logs: 'Logs',
                workflows: 'Automatizaciones',
                ai: 'IA',
            }
        },
        automations: {
            title: 'Automatizaciones',
            active: 'Bots activos',
            pageSubtitle: 'Flujos inteligentes que optimizan tu negocio y generan ingresos automáticamente',
            newButton: 'Nueva Automatización',
            ui: {
                searchLabel: 'Buscar automatizaciones',
                searchPlaceholder: 'Buscar por nombre, descripción o trigger...',
                categoryLabel: 'Categoría',
                categoryAll: 'Todas las categorías',
                statusLabel: 'Estado',
                statusAll: 'Todos los estados',
                statusActive: 'Activas',
                statusPaused: 'Pausadas',
                statusDraft: 'Borradores',
                logs: 'Logs',
                templates: 'Templates',
                categorySales: 'Ventas',
                categoryAi: 'IA',
                categoryOperations: 'Operaciones',
                categoryMarketing: 'Marketing',
            }
        },
        settings: {
            title: 'Ajustes',
            pageSubtitle: 'Gestiona tu cuenta, equipo, facturación y preferencias',
            profile: 'Perfil',
            company: 'Empresa',
            security: 'Seguridad',
            billing: 'Facturación',
            notifications: 'Notificaciones',
            team: 'Equipo',
            permissions: 'Permisos',
            plans: 'Planes',
            usage: 'Límites',
            appearance: 'Apariencia',
            dangerZone: 'Zona Peligrosa',
        },
        orders: {
            title: 'Pedidos',
            singular: 'Pedido',
            plural: 'Pedidos',
            status: {
                PENDING: 'Pendiente',
                RECEIVED: 'Recibido',
                COMPLETED: 'Completado',
                CANCELLED: 'Cancelado',
                PAID: 'Pagado',
                DELAYED: 'Retrasado',
            },
            types: {
                ONE_TIME: 'Puntual',
                RECURRING: 'Recurrente',
                ONE_OFF: 'Puntual',
                MATERIAL: 'Material',
                SERVICE: 'Servicio',
                SUBSCRIPTION: 'Suscripción',
            }
        },
        common: {
            save: 'Guardar',
            cancel: 'Cancelar',
            delete: 'Eliminar',
            edit: 'Editar',
            create: 'Crear',
            loading: 'Cargando...',
            error: 'Error',
            success: 'Éxito',
            confirm: 'Confirmar',
            search: 'Buscar',
            actions: 'Acciones',
            filter: 'Filtrar',
            noResults: 'No se encontraron resultados',
            viewAll: 'Ver todo',
            loadMore: 'Cargar más',
        }
    },

    features: {
        modules: {
            providers: true,
            clients: true,
            leads: true,
            sales: true,
            finance: true,
            billing: true,
            tasks: true,
            automations: true,
            aiInsights: true,
            analytics: true,
            reporting: true,
            integrations: true,
            notifications: true,
        },
        providers: {
            showOrders: true,
            showPayments: true,
            showTimeline: true,
            showFiles: true,
            showServices: true,
            showEconomicImpact: true,
            showStockRisk: true,
            allowAutoPayment: true,
        }
    }
};
