export type TemplateStyle = {
  headerBg: string
  headerText: string
  accentColor: string
  bodyBg: string
  bodyText: string
  tableBorderColor: string
  tableHeaderBg: string
  tableHeaderText: string
  tableAltRowBg: string
  fontFamily: string
  logoPosition: "left" | "center" | "right"
  qrPosition: "top-right" | "bottom-left" | "bottom-right"
  layout: "standard" | "compact" | "modern" | "minimal" | "luxury"
  showBorders: boolean
  roundedCorners: boolean
  [key: string]: unknown
}

export type InvoiceTemplateCatalog = {
  slug: string
  name: string
  description: string
  category: "free" | "premium"
  price: number
  isDefault?: boolean
  sortOrder: number
  style: TemplateStyle
}

export const INVOICE_TEMPLATES: InvoiceTemplateCatalog[] = [
  // ── GRATUITAS (15) ──────────────────────────────────────────────
  {
    slug: "clasica",
    name: "Clásica",
    description: "Diseño limpio y profesional. La plantilla por defecto.",
    category: "free",
    price: 0,
    isDefault: true,
    sortOrder: 0,
    style: {
      headerBg: "#0B1F2A",
      headerText: "#FFFFFF",
      accentColor: "#1FA97A",
      bodyBg: "#FFFFFF",
      bodyText: "#1E293B",
      tableBorderColor: "#E2E8F0",
      tableHeaderBg: "#0B1F2A",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#F8FAFB",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "top-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: true,
    },
  },
  {
    slug: "moderna",
    name: "Moderna",
    description: "Líneas limpias, tipografía grande, look contemporáneo.",
    category: "free",
    price: 0,
    sortOrder: 1,
    style: {
      headerBg: "#FFFFFF",
      headerText: "#111827",
      accentColor: "#3B82F6",
      bodyBg: "#FFFFFF",
      bodyText: "#374151",
      tableBorderColor: "#D1D5DB",
      tableHeaderBg: "#F3F4F6",
      tableHeaderText: "#111827",
      tableAltRowBg: "#F9FAFB",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "modern",
      showBorders: false,
      roundedCorners: true,
    },
  },
  {
    slug: "minimalista",
    name: "Minimalista",
    description: "Menos es más. Solo lo esencial, sin decoración.",
    category: "free",
    price: 0,
    sortOrder: 2,
    style: {
      headerBg: "#FFFFFF",
      headerText: "#000000",
      accentColor: "#000000",
      bodyBg: "#FFFFFF",
      bodyText: "#333333",
      tableBorderColor: "#000000",
      tableHeaderBg: "#FFFFFF",
      tableHeaderText: "#000000",
      tableAltRowBg: "#FFFFFF",
      fontFamily: "helvetica",
      logoPosition: "center",
      qrPosition: "bottom-left",
      layout: "minimal",
      showBorders: true,
      roundedCorners: false,
    },
  },
  {
    slug: "corporativa",
    name: "Corporativa",
    description: "Aspecto serio y empresarial. Ideal para pymes.",
    category: "free",
    price: 0,
    sortOrder: 3,
    style: {
      headerBg: "#1E3A5F",
      headerText: "#FFFFFF",
      accentColor: "#1E3A5F",
      bodyBg: "#FFFFFF",
      bodyText: "#1E293B",
      tableBorderColor: "#CBD5E1",
      tableHeaderBg: "#1E3A5F",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#F1F5F9",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "top-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: false,
    },
  },
  {
    slug: "verde-natura",
    name: "Verde Natura",
    description: "Tonos verdes naturales. Para negocios eco y sostenibles.",
    category: "free",
    price: 0,
    sortOrder: 4,
    style: {
      headerBg: "#064E3B",
      headerText: "#FFFFFF",
      accentColor: "#059669",
      bodyBg: "#FFFFFF",
      bodyText: "#1E293B",
      tableBorderColor: "#D1FAE5",
      tableHeaderBg: "#064E3B",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#ECFDF5",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: true,
    },
  },
  {
    slug: "roja-ejecutiva",
    name: "Roja Ejecutiva",
    description: "Cabecera roja intensa. Presencia y autoridad.",
    category: "free",
    price: 0,
    sortOrder: 5,
    style: {
      headerBg: "#991B1B",
      headerText: "#FFFFFF",
      accentColor: "#DC2626",
      bodyBg: "#FFFFFF",
      bodyText: "#1C1C1C",
      tableBorderColor: "#FCA5A5",
      tableHeaderBg: "#991B1B",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#FEF2F2",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: false,
    },
  },
  {
    slug: "azul-oceano",
    name: "Azul Océano",
    description: "Tonos azul profundo. Transmite confianza y calma.",
    category: "free",
    price: 0,
    sortOrder: 6,
    style: {
      headerBg: "#0C4A6E",
      headerText: "#FFFFFF",
      accentColor: "#0284C7",
      bodyBg: "#FFFFFF",
      bodyText: "#0F172A",
      tableBorderColor: "#BAE6FD",
      tableHeaderBg: "#0C4A6E",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#F0F9FF",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "top-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: true,
    },
  },
  {
    slug: "gris-industrial",
    name: "Gris Industrial",
    description: "Paleta gris y neutra. Para sectores técnicos e industriales.",
    category: "free",
    price: 0,
    sortOrder: 7,
    style: {
      headerBg: "#374151",
      headerText: "#F9FAFB",
      accentColor: "#6B7280",
      bodyBg: "#FFFFFF",
      bodyText: "#111827",
      tableBorderColor: "#D1D5DB",
      tableHeaderBg: "#374151",
      tableHeaderText: "#F9FAFB",
      tableAltRowBg: "#F3F4F6",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "compact",
      showBorders: true,
      roundedCorners: false,
    },
  },
  {
    slug: "naranja-creativa",
    name: "Naranja Creativa",
    description: "Energía y creatividad. Para agencias y freelancers.",
    category: "free",
    price: 0,
    sortOrder: 8,
    style: {
      headerBg: "#FFFFFF",
      headerText: "#111827",
      accentColor: "#EA580C",
      bodyBg: "#FFFFFF",
      bodyText: "#1C1917",
      tableBorderColor: "#FED7AA",
      tableHeaderBg: "#FFF7ED",
      tableHeaderText: "#9A3412",
      tableAltRowBg: "#FFFBF5",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "modern",
      showBorders: false,
      roundedCorners: true,
    },
  },
  {
    slug: "morada-elegante",
    name: "Morada Elegante",
    description: "Morado suave. Ideal para consultoría y servicios creativos.",
    category: "free",
    price: 0,
    sortOrder: 9,
    style: {
      headerBg: "#4C1D95",
      headerText: "#FFFFFF",
      accentColor: "#7C3AED",
      bodyBg: "#FFFFFF",
      bodyText: "#1E1B4B",
      tableBorderColor: "#DDD6FE",
      tableHeaderBg: "#4C1D95",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#F5F3FF",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "top-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: true,
    },
  },
  {
    slug: "dorada-premium",
    name: "Dorada",
    description: "Dorado cálido sobre negro. Para servicios de alto valor.",
    category: "free",
    price: 0,
    sortOrder: 10,
    style: {
      headerBg: "#1C1917",
      headerText: "#FCD34D",
      accentColor: "#D97706",
      bodyBg: "#FFFFFF",
      bodyText: "#1C1917",
      tableBorderColor: "#FDE68A",
      tableHeaderBg: "#1C1917",
      tableHeaderText: "#FCD34D",
      tableAltRowBg: "#FFFBEB",
      fontFamily: "helvetica",
      logoPosition: "center",
      qrPosition: "bottom-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: false,
    },
  },
  {
    slug: "rosa-suave",
    name: "Rosa Suave",
    description: "Tonos rosados delicados. Para salud, belleza y bienestar.",
    category: "free",
    price: 0,
    sortOrder: 11,
    style: {
      headerBg: "#FFFFFF",
      headerText: "#881337",
      accentColor: "#E11D48",
      bodyBg: "#FFFFFF",
      bodyText: "#1E1B4B",
      tableBorderColor: "#FECDD3",
      tableHeaderBg: "#FFF1F2",
      tableHeaderText: "#9F1239",
      tableAltRowBg: "#FFF5F6",
      fontFamily: "helvetica",
      logoPosition: "center",
      qrPosition: "bottom-right",
      layout: "modern",
      showBorders: false,
      roundedCorners: true,
    },
  },
  {
    slug: "turquesa-fresh",
    name: "Turquesa Fresh",
    description: "Fresca y moderna. Para negocios digitales y startups.",
    category: "free",
    price: 0,
    sortOrder: 12,
    style: {
      headerBg: "#0F766E",
      headerText: "#FFFFFF",
      accentColor: "#14B8A6",
      bodyBg: "#FFFFFF",
      bodyText: "#134E4A",
      tableBorderColor: "#99F6E4",
      tableHeaderBg: "#0F766E",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#F0FDFA",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "top-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: true,
    },
  },
  {
    slug: "carbon-oscura",
    name: "Carbón Oscura",
    description: "Modo oscuro total. Impacto visual máximo.",
    category: "free",
    price: 0,
    sortOrder: 13,
    style: {
      headerBg: "#18181B",
      headerText: "#F4F4F5",
      accentColor: "#A1A1AA",
      bodyBg: "#27272A",
      bodyText: "#F4F4F5",
      tableBorderColor: "#3F3F46",
      tableHeaderBg: "#18181B",
      tableHeaderText: "#F4F4F5",
      tableAltRowBg: "#1F1F23",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "compact",
      showBorders: true,
      roundedCorners: false,
    },
  },
  {
    slug: "duo-tone",
    name: "Duo Tone",
    description: "Dos colores en perfecta armonía. Equilibrio visual.",
    category: "free",
    price: 0,
    sortOrder: 14,
    style: {
      headerBg: "#F8FAFC",
      headerText: "#0F172A",
      accentColor: "#0F172A",
      bodyBg: "#FFFFFF",
      bodyText: "#0F172A",
      tableBorderColor: "#0F172A",
      tableHeaderBg: "#0F172A",
      tableHeaderText: "#F8FAFC",
      tableAltRowBg: "#F8FAFC",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: false,
    },
  },

  // ── PREMIUM (10) — 0,99€ ───────────────────────────────────────
  {
    slug: "premium-luxury",
    name: "Luxury Gold",
    description: "Bordes dorados, tipografía elegante. Para servicios de alto valor.",
    category: "premium",
    price: 0.99,
    sortOrder: 15,
    style: {
      headerBg: "#1A1A2E",
      headerText: "#C9A96E",
      accentColor: "#C9A96E",
      bodyBg: "#FFFFFF",
      bodyText: "#1A1A2E",
      tableBorderColor: "#C9A96E",
      tableHeaderBg: "#1A1A2E",
      tableHeaderText: "#C9A96E",
      tableAltRowBg: "#FDF9F0",
      fontFamily: "times",
      logoPosition: "center",
      qrPosition: "bottom-right",
      layout: "luxury",
      showBorders: true,
      roundedCorners: false,
      goldAccents: true,
    },
  },
  {
    slug: "premium-architect",
    name: "Architect",
    description: "Líneas arquitectónicas precisas. Para estudios y diseñadores.",
    category: "premium",
    price: 0.99,
    sortOrder: 16,
    style: {
      headerBg: "#FFFFFF",
      headerText: "#1A1A1A",
      accentColor: "#1A1A1A",
      bodyBg: "#FFFFFF",
      bodyText: "#1A1A1A",
      tableBorderColor: "#1A1A1A",
      tableHeaderBg: "#1A1A1A",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#FAFAFA",
      fontFamily: "helvetica",
      logoPosition: "right",
      qrPosition: "bottom-left",
      layout: "minimal",
      showBorders: true,
      roundedCorners: false,
      architectLines: true,
    },
  },
  {
    slug: "premium-studio",
    name: "Creative Studio",
    description: "Colores vibrantes y audaces. Para agencias creativas.",
    category: "premium",
    price: 0.99,
    sortOrder: 17,
    style: {
      headerBg: "#FF4D6D",
      headerText: "#FFFFFF",
      accentColor: "#FF4D6D",
      bodyBg: "#FFFFFF",
      bodyText: "#1A1A1A",
      tableBorderColor: "#FFB3C1",
      tableHeaderBg: "#FF4D6D",
      tableHeaderText: "#FFFFFF",
      tableAltRowBg: "#FFF5F7",
      fontFamily: "helvetica",
      logoPosition: "center",
      qrPosition: "bottom-right",
      layout: "modern",
      showBorders: false,
      roundedCorners: true,
      vibrantStyle: true,
    },
  },
  {
    slug: "premium-law",
    name: "Bufete",
    description: "Seria, clásica, con serif. Para abogados y notarías.",
    category: "premium",
    price: 0.99,
    sortOrder: 18,
    style: {
      headerBg: "#1C2833",
      headerText: "#F2F3F4",
      accentColor: "#1C2833",
      bodyBg: "#FFFFFF",
      bodyText: "#1C2833",
      tableBorderColor: "#AEB6BF",
      tableHeaderBg: "#1C2833",
      tableHeaderText: "#F2F3F4",
      tableAltRowBg: "#F8F9FA",
      fontFamily: "times",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: false,
      serifStyle: true,
    },
  },
  {
    slug: "premium-tech",
    name: "Tech Dark",
    description: "Futurista y digital. Para empresas tecnológicas.",
    category: "premium",
    price: 0.99,
    sortOrder: 19,
    style: {
      headerBg: "#0D1117",
      headerText: "#58A6FF",
      accentColor: "#58A6FF",
      bodyBg: "#0D1117",
      bodyText: "#C9D1D9",
      tableBorderColor: "#30363D",
      tableHeaderBg: "#161B22",
      tableHeaderText: "#58A6FF",
      tableAltRowBg: "#111B24",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "bottom-right",
      layout: "compact",
      showBorders: true,
      roundedCorners: true,
      techGlow: true,
    },
  },
  {
    slug: "premium-medical",
    name: "Clínica",
    description: "Limpia y de confianza. Para médicos y clínicas.",
    category: "premium",
    price: 0.99,
    sortOrder: 20,
    style: {
      headerBg: "#EFF6FF",
      headerText: "#1D4ED8",
      accentColor: "#2563EB",
      bodyBg: "#FFFFFF",
      bodyText: "#1E3A5F",
      tableBorderColor: "#BFDBFE",
      tableHeaderBg: "#DBEAFE",
      tableHeaderText: "#1D4ED8",
      tableAltRowBg: "#F8FBFF",
      fontFamily: "helvetica",
      logoPosition: "center",
      qrPosition: "bottom-right",
      layout: "modern",
      showBorders: false,
      roundedCorners: true,
      medicalStyle: true,
    },
  },
  {
    slug: "premium-consulting",
    name: "Executive",
    description: "Gris oscuro, máxima sobriedad ejecutiva.",
    category: "premium",
    price: 0.99,
    sortOrder: 21,
    style: {
      headerBg: "#1F2937",
      headerText: "#F9FAFB",
      accentColor: "#6366F1",
      bodyBg: "#FFFFFF",
      bodyText: "#111827",
      tableBorderColor: "#E5E7EB",
      tableHeaderBg: "#1F2937",
      tableHeaderText: "#F9FAFB",
      tableAltRowBg: "#F9FAFB",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "top-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: false,
      executiveStyle: true,
    },
  },
  {
    slug: "premium-fashion",
    name: "Fashion",
    description: "Tipografía fina y elegante. Para moda y lifestyle.",
    category: "premium",
    price: 0.99,
    sortOrder: 22,
    style: {
      headerBg: "#FAF7F5",
      headerText: "#1A1A1A",
      accentColor: "#B5838D",
      bodyBg: "#FAF7F5",
      bodyText: "#1A1A1A",
      tableBorderColor: "#E8D5B7",
      tableHeaderBg: "#FAF7F5",
      tableHeaderText: "#1A1A1A",
      tableAltRowBg: "#F5F0EB",
      fontFamily: "helvetica",
      logoPosition: "center",
      qrPosition: "bottom-right",
      layout: "minimal",
      showBorders: false,
      roundedCorners: false,
      fashionStyle: true,
    },
  },
  {
    slug: "premium-restaurant",
    name: "Restaurante",
    description: "Cálida y acogedora. Para restaurantes y catering.",
    category: "premium",
    price: 0.99,
    sortOrder: 23,
    style: {
      headerBg: "#78350F",
      headerText: "#FEF3C7",
      accentColor: "#D97706",
      bodyBg: "#FFFBEB",
      bodyText: "#292524",
      tableBorderColor: "#FDE68A",
      tableHeaderBg: "#78350F",
      tableHeaderText: "#FEF3C7",
      tableAltRowBg: "#FFFDF5",
      fontFamily: "helvetica",
      logoPosition: "center",
      qrPosition: "bottom-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: true,
      warmStyle: true,
    },
  },
  {
    slug: "premium-construction",
    name: "Construcción",
    description: "Robusta y directa. Para construcción y reformas.",
    category: "premium",
    price: 0.99,
    sortOrder: 24,
    style: {
      headerBg: "#431407",
      headerText: "#FFF7ED",
      accentColor: "#EA580C",
      bodyBg: "#FFFFFF",
      bodyText: "#1C1917",
      tableBorderColor: "#FED7AA",
      tableHeaderBg: "#431407",
      tableHeaderText: "#FFF7ED",
      tableAltRowBg: "#FFF7F0",
      fontFamily: "helvetica",
      logoPosition: "left",
      qrPosition: "top-right",
      layout: "standard",
      showBorders: true,
      roundedCorners: false,
      industrialStyle: true,
    },
  },
]

export const PREMIUM_PACK_PRICE = 14.99
export const PREMIUM_TEMPLATES = INVOICE_TEMPLATES.filter(t => t.category === "premium")
export const FREE_TEMPLATES = INVOICE_TEMPLATES.filter(t => t.category === "free")
export const DEFAULT_TEMPLATE = INVOICE_TEMPLATES.find(t => t.isDefault) ?? INVOICE_TEMPLATES[0]
