export type ConnectType = "web_sdk" | "oauth" | "apikey" | "webhook" | "coming_soon"
export type CategoryId = "leads" | "email" | "calendar" | "automation" | "payments" | "productivity"
export type IntegrationStatus = "connected" | "disconnected" | "error" | "coming_soon"

export interface IntegrationDef {
  id: string
  name: string
  category: CategoryId
  description: string
  benefit: string // what it unlocks in ClientLabs
  connectType: ConnectType
  color: string // tailwind bg class for icon area
  textColor: string // tailwind text class
  initials: string // fallback brand initial
  status: IntegrationStatus
}

export const CATEGORIES: { id: CategoryId | "all"; label: string }[] = [
  { id: "all", label: "Todas" },
  { id: "leads", label: "Captación" },
  { id: "email", label: "Email" },
  { id: "calendar", label: "Calendario" },
  { id: "automation", label: "Automatización" },
  { id: "payments", label: "Pagos" },
  { id: "productivity", label: "Productividad" },
]

export const INTEGRATIONS: IntegrationDef[] = [
  // ─── Captación de leads ───────────────────────────────────────────
  {
    id: "web",
    name: "Web Ingestion",
    category: "leads",
    description: "Captura leads desde formularios de tu sitio web o landings con el SDK de ClientLabs.",
    benefit: "Los leads del sitio entran directamente al CRM con fuente y metadata.",
    connectType: "web_sdk",
    color: "bg-[#E8F5EF]",
    textColor: "text-[#1FA97A]",
    initials: "W",
    status: "disconnected",
  },
  {
    id: "whatsapp",
    name: "WhatsApp Business",
    category: "leads",
    description: "Sincroniza tu cuenta oficial de WhatsApp Business API para capturar conversaciones como leads.",
    benefit: "Cada conversación nueva crea un lead automático con historial de chat.",
    connectType: "coming_soon",
    color: "bg-green-50",
    textColor: "text-green-600",
    initials: "W",
    status: "coming_soon",
  },
  {
    id: "facebook",
    name: "Meta Lead Ads",
    category: "leads",
    description: "Conecta tus campañas de Lead Generation de Facebook e Instagram para sincronizar en tiempo real.",
    benefit: "Los leads de tus anuncios llegan al CRM en segundos, sin CSV manual.",
    connectType: "coming_soon",
    color: "bg-blue-50",
    textColor: "text-blue-600",
    initials: "M",
    status: "coming_soon",
  },
  {
    id: "google-ads",
    name: "Google Ads",
    category: "leads",
    description: "Importa leads de tus formularios de Google Ads (Lead Form Extensions) directamente.",
    benefit: "Atribuye el origen de cada lead a la campaña y keyword exacta.",
    connectType: "oauth",
    color: "bg-red-50",
    textColor: "text-red-500",
    initials: "G",
    status: "coming_soon",
  },
  {
    id: "linkedin",
    name: "LinkedIn Lead Gen",
    category: "leads",
    description: "Sincroniza los formularios nativos de LinkedIn Lead Gen Forms con tu pipeline.",
    benefit: "Leads B2B de alto valor con datos profesionales completos.",
    connectType: "oauth",
    color: "bg-sky-50",
    textColor: "text-sky-600",
    initials: "in",
    status: "coming_soon",
  },
  {
    id: "tiktok",
    name: "TikTok Lead Gen",
    category: "leads",
    description: "Captura leads de tus campañas de TikTok Lead Generation en tiempo real.",
    benefit: "Audiencias jóvenes en el CRM sin fricción manual.",
    connectType: "webhook",
    color: "bg-zinc-100",
    textColor: "text-zinc-800",
    initials: "Tk",
    status: "coming_soon",
  },

  // ─── Email ────────────────────────────────────────────────────────
  {
    id: "gmail",
    name: "Gmail / Google Workspace",
    category: "email",
    description: "Sincroniza tu bandeja de Gmail para registrar comunicaciones con leads y clientes automáticamente.",
    benefit: "Cada email enviado o recibido queda registrado en la ficha del contacto.",
    connectType: "oauth",
    color: "bg-red-50",
    textColor: "text-red-500",
    initials: "G",
    status: "disconnected",
  },
  {
    id: "outlook",
    name: "Outlook / Microsoft 365",
    category: "email",
    description: "Integra tu cuenta de Outlook o Exchange para sincronizar emails y calendario.",
    benefit: "Historial completo de comunicación por cliente en un solo lugar.",
    connectType: "oauth",
    color: "bg-blue-50",
    textColor: "text-blue-600",
    initials: "O",
    status: "coming_soon",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    category: "email",
    description: "Conecta tus audiencias de Mailchimp para sincronizar suscriptores como contactos en ClientLabs.",
    benefit: "Segmentación cruzada entre tu base de email marketing y el CRM.",
    connectType: "apikey",
    color: "bg-yellow-50",
    textColor: "text-yellow-600",
    initials: "Mc",
    status: "disconnected",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "email",
    description: "Usa SendGrid como motor de envío para los emails automatizados que lanza ClientLabs.",
    benefit: "Emails transaccionales y de automatización con alta deliverability.",
    connectType: "apikey",
    color: "bg-teal-50",
    textColor: "text-teal-600",
    initials: "Sg",
    status: "disconnected",
  },

  // ─── Calendario ───────────────────────────────────────────────────
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "calendar",
    description: "Sincroniza tus tareas y reuniones de ClientLabs con Google Calendar en ambas direcciones.",
    benefit: "Tareas con fecha límite aparecen en tu calendario. Reuniones crean automáticamente tareas.",
    connectType: "oauth",
    color: "bg-red-50",
    textColor: "text-red-500",
    initials: "GC",
    status: "disconnected",
  },
  {
    id: "calendly",
    name: "Calendly",
    category: "calendar",
    description: "Cuando alguien reserva una reunión en Calendly, crea el contacto y la tarea en ClientLabs.",
    benefit: "Cero fricción entre que un lead agenda y que aparece en tu pipeline.",
    connectType: "webhook",
    color: "bg-blue-50",
    textColor: "text-blue-600",
    initials: "Ca",
    status: "disconnected",
  },
  {
    id: "cal",
    name: "Cal.com",
    category: "calendar",
    description: "Alternativa open-source a Calendly con integración webhook directa.",
    benefit: "Reservas convertidas en leads y tareas de forma automática.",
    connectType: "webhook",
    color: "bg-gray-100",
    textColor: "text-gray-700",
    initials: "Cal",
    status: "coming_soon",
  },

  // ─── Automatización ───────────────────────────────────────────────
  {
    id: "zapier",
    name: "Zapier",
    category: "automation",
    description: "Conecta ClientLabs con más de 6.000 apps mediante Zaps. Trigger o acción en cualquier flujo.",
    benefit: "Automatiza sin código entre ClientLabs y cualquier herramienta de tu stack.",
    connectType: "apikey",
    color: "bg-orange-50",
    textColor: "text-orange-500",
    initials: "Z",
    status: "disconnected",
  },
  {
    id: "make",
    name: "Make (Integromat)",
    category: "automation",
    description: "Crea escenarios avanzados de automatización visual con ClientLabs como nodo.",
    benefit: "Flujos complejos con lógica condicional entre ClientLabs y tu stack.",
    connectType: "webhook",
    color: "bg-purple-50",
    textColor: "text-purple-600",
    initials: "Mk",
    status: "disconnected",
  },
  {
    id: "n8n",
    name: "n8n",
    category: "automation",
    description: "Plataforma de automatización self-hosted. Conecta ClientLabs mediante webhooks y API REST.",
    benefit: "Automatizaciones avanzadas para equipos técnicos con control total.",
    connectType: "apikey",
    color: "bg-rose-50",
    textColor: "text-rose-600",
    initials: "n8",
    status: "coming_soon",
  },

  // ─── Pagos ────────────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Sincroniza pagos, facturas y suscripciones de Stripe con el módulo financiero de ClientLabs.",
    benefit: "Cada pago actualiza automáticamente el estado del cliente y genera un movimiento en finanzas.",
    connectType: "apikey",
    color: "bg-indigo-50",
    textColor: "text-indigo-600",
    initials: "S",
    status: "disconnected",
  },
  {
    id: "paypal",
    name: "PayPal",
    category: "payments",
    description: "Recibe webhooks de PayPal para registrar cobros en el historial financiero del cliente.",
    benefit: "Cobros de PayPal reflejados en tiempo real en el dashboard de finanzas.",
    connectType: "webhook",
    color: "bg-blue-50",
    textColor: "text-blue-700",
    initials: "PP",
    status: "coming_soon",
  },

  // ─── Productividad ────────────────────────────────────────────────
  {
    id: "slack",
    name: "Slack",
    category: "productivity",
    description: "Recibe notificaciones de ClientLabs en canales de Slack: leads nuevos, tareas urgentes, cobros.",
    benefit: "El equipo se entera al instante de lo que pasa sin entrar al dashboard.",
    connectType: "webhook",
    color: "bg-purple-50",
    textColor: "text-purple-600",
    initials: "Sl",
    status: "disconnected",
  },
  {
    id: "notion",
    name: "Notion",
    category: "productivity",
    description: "Exporta clientes, tareas y proyectos de ClientLabs a bases de datos de Notion.",
    benefit: "Documentación de proyectos sincronizada con el CRM.",
    connectType: "apikey",
    color: "bg-gray-100",
    textColor: "text-gray-800",
    initials: "N",
    status: "disconnected",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "productivity",
    description: "Adjunta documentos de Drive a fichas de clientes y tareas directamente desde ClientLabs.",
    benefit: "Contratos, propuestas y archivos vinculados al cliente sin cambiar de herramienta.",
    connectType: "oauth",
    color: "bg-green-50",
    textColor: "text-green-600",
    initials: "GD",
    status: "coming_soon",
  },
]
