-- Add missing Task columns (all nullable for backward compatibility).
-- No tables dropped, no data lost. Safe to run on existing DB.

-- Scalars
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "estimatedMinutes" INTEGER;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "priorityScore" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "energyScore" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "financialImpact" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "isBlocking" BOOLEAN;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "blockedReason" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "recurrenceRule" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "sourceModule" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "sourceId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "completionQualityScore" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;

-- Self-relation: parentTaskId (nullable FK to Task)
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "parentTaskId" TEXT;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Task_parentTaskId_fkey'
  ) THEN
    ALTER TABLE "Task" ADD CONSTRAINT "Task_parentTaskId_fkey"
      FOREIGN KEY ("parentTaskId") REFERENCES "Task"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- Indexes (IF NOT EXISTS for idempotency)
CREATE INDEX IF NOT EXISTS "Task_assignedTo_idx" ON "Task"("assignedTo");
CREATE INDEX IF NOT EXISTS "Task_priorityScore_idx" ON "Task"("priorityScore");
CREATE INDEX IF NOT EXISTS "Task_parentTaskId_idx" ON "Task"("parentTaskId");
CREATE INDEX IF NOT EXISTS "Task_sourceModule_idx" ON "Task"("sourceModule");
CREATE INDEX IF NOT EXISTS "Task_completedAt_idx" ON "Task"("completedAt");
